spring.application.name=healthcore

spring.datasource.url=jdbc:postgresql://localhost:5432/healthcore
spring.datasource.username=postgres
spring.datasource.password=DATABASE1895
# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always