HealthCore: it.unitn.healthcore.domain.EmployeeRegistrationForm Class Reference
it.unitn.healthcore.domain.EmployeeRegistrationForm Class Reference
Public Member Functions
EmployeeRegistrationForm ()
EmployeeRegistrationForm (String email, String password, String passwordConfirmation, String name, String surname, String role, Integer departmentId)
EmployeeRegistrationForm (String email, String password, String passwordConfirmation, String name, String role, String surname)
String getName ()
void setName (String name)
String getSurname ()
void setSurname (String surname)
String getRole ()
void setRole (String role)
Integer getDepartmentId ()
void setDepartmentId (Integer departmentId)
Public Member Functions inherited from it.unitn.healthcore.domain.PasswordConfirmationForm
PasswordConfirmationForm ()
PasswordConfirmationForm (String email, String password, String passwordConfirmation)
String getEmail ()
void setEmail (String email)
String getPassword ()
void setPassword (String password)
String getPasswordConfirmation ()
void setPasswordConfirmation (String passwordConfirmation)
Detailed Description
Definition at line 3 of file EmployeeRegistrationForm.java.
Constructor & Destructor Documentation
EmployeeRegistrationForm() [1/3]
it.unitn.healthcore.domain.EmployeeRegistrationForm.EmployeeRegistrationForm ()
Definition at line 10 of file EmployeeRegistrationForm.java.
EmployeeRegistrationForm() [2/3]
it.unitn.healthcore.domain.EmployeeRegistrationForm.EmployeeRegistrationForm (String email, String password, String passwordConfirmation, String name, String surname, String role, Integer departmentId)
Definition at line 12 of file EmployeeRegistrationForm.java.
EmployeeRegistrationForm() [3/3]
it.unitn.healthcore.domain.EmployeeRegistrationForm.EmployeeRegistrationForm (String email, String password, String passwordConfirmation, String name, String role, String surname)
Definition at line 20 of file EmployeeRegistrationForm.java.
Member Function Documentation
getDepartmentId()
Integer it.unitn.healthcore.domain.EmployeeRegistrationForm.getDepartmentId ()
Definition at line 53 of file EmployeeRegistrationForm.java.
Referenced by it.unitn.healthcore.business.UserService.registerDoctor().
getName()
String it.unitn.healthcore.domain.EmployeeRegistrationForm.getName ()
Definition at line 29 of file EmployeeRegistrationForm.java.
Referenced by it.unitn.healthcore.business.UserService.registerAdministrator(), and it.unitn.healthcore.business.UserService.registerDoctor().
getRole()
String it.unitn.healthcore.domain.EmployeeRegistrationForm.getRole ()
Definition at line 45 of file EmployeeRegistrationForm.java.
Referenced by it.unitn.healthcore.business.UserService.registerEmployee().
getSurname()
String it.unitn.healthcore.domain.EmployeeRegistrationForm.getSurname ()
Definition at line 37 of file EmployeeRegistrationForm.java.
Referenced by it.unitn.healthcore.business.UserService.registerAdministrator(), and it.unitn.healthcore.business.UserService.registerDoctor().
setDepartmentId()
void it.unitn.healthcore.domain.EmployeeRegistrationForm.setDepartmentId (Integer departmentId)
Definition at line 57 of file EmployeeRegistrationForm.java.
setName()
void it.unitn.healthcore.domain.EmployeeRegistrationForm.setName (String name)
Definition at line 33 of file EmployeeRegistrationForm.java.
setRole()
void it.unitn.healthcore.domain.EmployeeRegistrationForm.setRole (String role)
Definition at line 49 of file EmployeeRegistrationForm.java.
setSurname()
void it.unitn.healthcore.domain.EmployeeRegistrationForm.setSurname (String surname)
Definition at line 41 of file EmployeeRegistrationForm.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/EmployeeRegistrationForm.java