HealthCore: it.unitn.healthcore.controller.DoctorController Class Reference
it.unitn.healthcore.controller.DoctorController Class Reference
Public Member Functions
DoctorController (DoctorService doctorService, AppointmentService appointmentService)
Constructor for the DoctorController class.
String viewDoctors ()
Retrieves a list of all doctors in the system.
Doctor viewDoctorManagementPage (@PathVariable("userId") Integer id)
Retrieves the details of a specific doctor by their ID.
void addShiftTime (@PathVariable("userId") Integer id, @RequestParam LocalDateTime startTime, @RequestParam LocalDateTime endTime)
Adds a new shift for a doctor.
void modifyShift (@PathVariable Integer shiftId, @RequestParam LocalDateTime startTime, @RequestParam LocalDateTime endTime)
Modifies an existing shift for a doctor.
void deleteShift (@PathVariable Integer shiftId)
Deletes an existing shift for a doctor.
List< Shift > viewMyShifts ()
Retrieves the details of a specific appointment by its ID.
String viewFutureAppointments ()
Retrieves a list of future appointments for the currently authenticated doctor.
String viewPastAppointments ()
Retrieves a list of past appointments for the currently authenticated doctor.
String viewAppointmentDetail (@PathVariable Integer appointmentId)
Retrieves the details of a specific appointment by its ID.
List< Department > viewAvailableDepartments ()
Retrieves a list of available departments for doctor assignment.
void changeDepartment (@PathVariable Integer doctorId, @RequestParam Integer departmentId)
Changes the department assignment for a specific doctor.
Detailed Description
Definition at line 23 of file DoctorController.java.
Constructor & Destructor Documentation
DoctorController()
it.unitn.healthcore.controller.DoctorController.DoctorController (DoctorService doctorService, AppointmentService appointmentService)
Constructor for the DoctorController class.
This constructor is used to inject the DoctorService and AppointmentService dependencies into the controller. The @Autowired annotation allows Spring to automatically wire the services when creating an instance of the controller.
Parameters
doctorService The service that provides business logic related to doctors.
appointmentService The service that provides business logic related to appointments.
Definition at line 33 of file DoctorController.java.
Member Function Documentation
addShiftTime()
void it.unitn.healthcore.controller.DoctorController.addShiftTime (@PathVariable("userId") Integer id, @RequestParam LocalDateTime startTime, @RequestParam LocalDateTime endTime)
Adds a new shift for a doctor.
This endpoint is accessible only to users with the 'ADMINISTRATOR' role. It takes the doctor's ID, the start time, and the end time of the shift as parameters. The method calls the DoctorService to add the shift to the specified doctor.
Parameters
id The ID of the doctor for whom to add the shift.
startTime The start time of the shift.
endTime The end time of the shift.
Definition at line 78 of file DoctorController.java.
References it.unitn.healthcore.business.DoctorService.addShift().
changeDepartment()
void it.unitn.healthcore.controller.DoctorController.changeDepartment (@PathVariable Integer doctorId, @RequestParam Integer departmentId)
Changes the department assignment for a specific doctor.
This endpoint is accessible only to users with the 'ADMINISTRATOR' role. It takes the doctor's ID and the new department ID as parameters and calls the DoctorService to update the doctor's department assignment.
Parameters
doctorId The ID of the doctor whose department is to be changed.
departmentId The ID of the new department to assign to the doctor.
Definition at line 196 of file DoctorController.java.
References it.unitn.healthcore.business.DoctorService.changeDepartment().
deleteShift()
void it.unitn.healthcore.controller.DoctorController.deleteShift (@PathVariable Integer shiftId)
Deletes an existing shift for a doctor.
This endpoint is accessible only to users with the 'ADMINISTRATOR' role. It takes the shift's ID as a parameter and calls the DoctorService to remove the specified shift from the system.
Parameters
shiftId The ID of the shift to delete.
Definition at line 103 of file DoctorController.java.
References it.unitn.healthcore.business.DoctorService.deleteShift().
modifyShift()
void it.unitn.healthcore.controller.DoctorController.modifyShift (@PathVariable Integer shiftId, @RequestParam LocalDateTime startTime, @RequestParam LocalDateTime endTime)
Modifies an existing shift for a doctor.
This endpoint is accessible only to users with the 'ADMINISTRATOR' role. It takes the shift's ID, the new start time, and the new end time as parameters. The method calls the DoctorService to update the specified shift with the new times.
Parameters
shiftId The ID of the shift to modify.
startTime The new start time of the shift.
endTime The new end time of the shift.
Definition at line 92 of file DoctorController.java.
References it.unitn.healthcore.business.DoctorService.modifyShift().
viewAppointmentDetail()
String it.unitn.healthcore.controller.DoctorController.viewAppointmentDetail (@PathVariable Integer appointmentId)
Retrieves the details of a specific appointment by its ID.
This endpoint is accessible only to users with the 'DOCTOR' role. It returns a string containing the details of the appointment, including patient information, diagnosis history, and any notes associated with the appointment.
Parameters
appointmentId The ID of the appointment to retrieve.
Returns
A string containing the details of the specified appointment.
Definition at line 174 of file DoctorController.java.
References it.unitn.healthcore.business.AppointmentService.getAppointmentDetails().
viewAvailableDepartments()
List<Department> it.unitn.healthcore.controller.DoctorController.viewAvailableDepartments ()
Retrieves a list of available departments for doctor assignment.
This endpoint is accessible only to users with the 'ADMINISTRATOR' role. It returns a list of Department objects representing the available departments in the system.
Returns
A list of Department objects representing available departments.
Definition at line 184 of file DoctorController.java.
References it.unitn.healthcore.business.DoctorService.getAvailableDepartments().
viewDoctorManagementPage()
Doctor it.unitn.healthcore.controller.DoctorController.viewDoctorManagementPage (@PathVariable("userId") Integer id)
Retrieves the details of a specific doctor by their ID.
This endpoint is accessible only to users with the 'ADMINISTRATOR' role. It returns a Doctor object containing the doctor's details.
Parameters
id The ID of the doctor to retrieve.
Returns
A Doctor object with the specified ID.
Definition at line 65 of file DoctorController.java.
References it.unitn.healthcore.business.DoctorService.findDoctor().
viewDoctors()
String it.unitn.healthcore.controller.DoctorController.viewDoctors ()
Retrieves a list of all doctors in the system.
This endpoint is accessible to users with the 'ADMINISTRATOR' or 'PATIENT' role. It returns a string representation of each doctor's ID, name, surname, and email.
Returns
A string containing the details of all doctors.
Definition at line 44 of file DoctorController.java.
References it.unitn.healthcore.business.DoctorService.getAllDoctors().
viewFutureAppointments()
String it.unitn.healthcore.controller.DoctorController.viewFutureAppointments ()
Retrieves a list of future appointments for the currently authenticated doctor.
This endpoint is accessible only to users with the 'DOCTOR' role. It returns a string representation of each future appointment, including the appointment ID, start and end times, and patient information.
Returns
A string containing the details of future appointments for the doctor.
Definition at line 127 of file DoctorController.java.
References it.unitn.healthcore.business.AppointmentService.getFutureAppointments().
viewMyShifts()
List<Shift> it.unitn.healthcore.controller.DoctorController.viewMyShifts ()
Retrieves the details of a specific appointment by its ID.
This endpoint is accessible only to users with the 'DOCTOR' role. It returns a string containing the details of the appointment, including patient information, diagnosis history, and any notes associated with the appointment.
Parameters
appointmentId The ID of the appointment to retrieve.
Returns
A string containing the details of the specified appointment.
Definition at line 115 of file DoctorController.java.
References it.unitn.healthcore.business.DoctorService.getCurrentDoctorShifts().
viewPastAppointments()
String it.unitn.healthcore.controller.DoctorController.viewPastAppointments ()
Retrieves a list of past appointments for the currently authenticated doctor.
This endpoint is accessible only to users with the 'DOCTOR' role. It returns a string representation of each past appointment, including the appointment ID, start and end times, and patient information.
Returns
A string containing the details of past appointments for the doctor.
Definition at line 150 of file DoctorController.java.
References it.unitn.healthcore.business.AppointmentService.getPastAppointments().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/controller/DoctorController.java