HealthCore: it.unitn.healthcore.business.UserService Class Reference
it.unitn.healthcore.business.UserService Class Reference
This class serves as a service layer for handling user-related business logic such as registration, profile updates, password recovery, and OTP verification.
Public Member Functions
UserService (UserRepository userRepository, PatientRepository patientRepository, DepartmentRepository departmentRepository)
Constructor for the UserService class.
UserDetails loadUserByUsername (String username) throws UsernameNotFoundException
Loads a user by their username (email) for authentication purposes.
Boolean verifyOtp (String otp)
Verifies the provided OTP (One-Time Password) for user authentication or password recovery.
void sendOtp (String email)
Sends an OTP (One-Time Password) to the specified email address for user authentication or password recovery.
String getCurrentUserEmail ()
Retrieves the email of the currently authenticated user.
User getCurrentUser ()
Retrieves the currently authenticated user from the database.
void registerPatient (PatientRegistrationForm user)
Registers a new patient in the system.
void registerEmployee (EmployeeRegistrationForm user)
Registers a new employee (doctor or administrator) in the system.
void registerDoctor (EmployeeRegistrationForm user)
Registers a new doctor in the system.
void registerAdministrator (EmployeeRegistrationForm user)
Registers a new administrator in the system.
void recoverPassword (PasswordConfirmationForm request)
Recovers the password for a user by verifying the OTP and updating the password in the database.
void deleteUser (Integer id)
Deletes a user from the system based on their ID.
void updateUserProfile (ProfileUpdateForm form)
Updates the profile of the currently authenticated user based on the provided object .
Detailed Description
This class serves as a service layer for handling user-related business logic such as registration, profile updates, password recovery, and OTP verification.
It interacts with the UserRepository and PatientRepository to perform database operations related to users. It also implements the UserDetailsService interface to integrate with Spring Security for authentication purposes.
See also
it.unitn.healthcore.persistence.UserRepository
it.unitn.healthcore.persistence.PatientRepository
Author
HealthCore Team
Version
1.0.0
Date
2026-06-11
Definition at line 35 of file UserService.java.
Constructor & Destructor Documentation
UserService()
it.unitn.healthcore.business.UserService.UserService (UserRepository userRepository, PatientRepository patientRepository, DepartmentRepository departmentRepository)
Constructor for the UserService class.
This constructor is used to inject the UserRepository, PatientRepository, and DepartmentRepository dependencies into the service. The @Autowired annotation allows Spring to automatically wire the repositories when creating an instance of the service.
Parameters
userRepository The repository that provides CRUD operations for User entities.
patientRepository The repository that provides CRUD operations for Patient entities.
departmentRepository The repository that provides CRUD operations for Department entities.
Definition at line 51 of file UserService.java.
Member Function Documentation
deleteUser()
void it.unitn.healthcore.business.UserService.deleteUser (Integer id)
Deletes a user from the system based on their ID.
This method checks if a user with the provided ID exists in the database. If the user is found, it deletes the user from the database. If no user is found with the provided ID, it throws a ResponseStatusException with a 404 NOT FOUND status.
Parameters
id The ID of the user to be deleted.
Exceptions
ResponseStatusException if no user is found with the provided ID.
Definition at line 266 of file UserService.java.
Referenced by it.unitn.healthcore.controller.UserController.deleteAccount().
getCurrentUser()
User it.unitn.healthcore.business.UserService.getCurrentUser ()
Retrieves the currently authenticated user from the database.
This method first obtains the email of the currently authenticated user using the getCurrentUserEmail() method. It then searches for a user in the database based on that email. If a user is found, it returns the User object; otherwise, it throws an IllegalStateException indicating that no user was found or no email was found.
Returns
The User object representing the currently authenticated user.
Exceptions
IllegalStateException if no user is found with the current email or if no email is available.
Definition at line 126 of file UserService.java.
References it.unitn.healthcore.persistence.UserRepository.findUserByEmail(), and it.unitn.healthcore.business.UserService.getCurrentUserEmail().
Referenced by it.unitn.healthcore.business.PatientService.bookAppointment(), it.unitn.healthcore.business.PatientService.cancelAppointment(), it.unitn.healthcore.controller.UserController.deleteAccount(), it.unitn.healthcore.business.AppointmentService.getAppointmentDetails(), it.unitn.healthcore.business.DoctorService.getCurrentDoctorShifts(), it.unitn.healthcore.business.PatientService.getCurrentInsurancePlan(), it.unitn.healthcore.business.AppointmentService.getFutureAppointments(), it.unitn.healthcore.business.AppointmentService.getPastAppointments(), it.unitn.healthcore.business.PatientService.modifyAppointment(), it.unitn.healthcore.business.PatientService.updateInsurancePlan(), it.unitn.healthcore.business.UserService.updateUserProfile(), it.unitn.healthcore.controller.UserController.userHomepage(), and it.unitn.healthcore.controller.UserController.viewProfile().
getCurrentUserEmail()
String it.unitn.healthcore.business.UserService.getCurrentUserEmail ()
Retrieves the email of the currently authenticated user.
This method accesses the SecurityContext to obtain the authentication details of the currently logged-in user. If a user is authenticated, it returns their email (username); otherwise, it returns null. This method is useful for identifying the current user in various service methods that require user-specific operations.
Returns
The email of the currently authenticated user, or null if no user is authenticated.
Definition at line 112 of file UserService.java.
Referenced by it.unitn.healthcore.business.UserService.getCurrentUser().
loadUserByUsername()
UserDetails it.unitn.healthcore.business.UserService.loadUserByUsername (String username) throws UsernameNotFoundException
Loads a user by their username (email) for authentication purposes.
This method is part of the UserDetailsService interface and is used by Spring Security to retrieve user details during the authentication process. It searches for a user in the database based on the provided email (username). If the user is found, it returns a SecurityUser object containing the user's details; otherwise, it throws a UsernameNotFoundException.
Parameters
username The email of the user to be loaded.
Returns
A UserDetails object containing the user's details for authentication.
Exceptions
UsernameNotFoundException if no user is found with the provided email.
Definition at line 65 of file UserService.java.
References it.unitn.healthcore.persistence.UserRepository.findUserByEmail().
recoverPassword()
void it.unitn.healthcore.business.UserService.recoverPassword (PasswordConfirmationForm request)
Recovers the password for a user by verifying the OTP and updating the password in the database.
This method first checks if the OTP has been verified. If not, it throws a ResponseStatusException with a 401 UNAUTHORIZED status. It then validates the password form and retrieves the user based on the provided email. If the user is found, it encodes the new password and updates it in the database. If the user is not found, it throws a ResponseStatusException with a 404 NOT FOUND status.
Parameters
request The PasswordConfirmationForm object containing the user's email and new password details.
Exceptions
ResponseStatusException if the OTP is not verified or if the user is not found.
Definition at line 238 of file UserService.java.
References it.unitn.healthcore.persistence.UserRepository.findUserByEmail(), it.unitn.healthcore.domain.PasswordConfirmationForm.getEmail(), it.unitn.healthcore.domain.PasswordConfirmationForm.getPassword(), it.unitn.healthcore.domain.PasswordConfirmationForm.isValidPasswordForm(), and it.unitn.healthcore.domain.User.setPassword().
Referenced by it.unitn.healthcore.controller.UserController.recoverPassword(), and it.unitn.healthcore.business.UserService.updateUserProfile().
registerAdministrator()
void it.unitn.healthcore.business.UserService.registerAdministrator (EmployeeRegistrationForm user)
Registers a new administrator in the system.
This method creates a new Administrator object and calls the registerUser() method to save the new administrator to the database. It does not perform any additional validation or checks, as administrators do not have associated departments or staff positions.
Parameters
user The EmployeeRegistrationForm object containing the administrator's registration details.
Definition at line 226 of file UserService.java.
References it.unitn.healthcore.domain.PasswordConfirmationForm.getEmail(), it.unitn.healthcore.domain.EmployeeRegistrationForm.getName(), it.unitn.healthcore.domain.PasswordConfirmationForm.getPassword(), and it.unitn.healthcore.domain.EmployeeRegistrationForm.getSurname().
Referenced by it.unitn.healthcore.business.UserService.registerEmployee().
registerDoctor()
void it.unitn.healthcore.business.UserService.registerDoctor (EmployeeRegistrationForm user)
Registers a new doctor in the system.
This method retrieves the department associated with the doctor from the database and checks if there are available staff positions in that department. If the department has available positions, it creates a new Doctor object and calls the registerUser() method to save the new doctor to the database. If the department is not found or has no available positions, it throws a ResponseStatusException with an appropriate status code and message.
Parameters
user The EmployeeRegistrationForm object containing the doctor's registration details.
Exceptions
ResponseStatusException if the department is not found or has no available staff positions.
Definition at line 206 of file UserService.java.
References it.unitn.healthcore.domain.EmployeeRegistrationForm.getDepartmentId(), it.unitn.healthcore.domain.Department.getDoctors(), it.unitn.healthcore.domain.PasswordConfirmationForm.getEmail(), it.unitn.healthcore.domain.EmployeeRegistrationForm.getName(), it.unitn.healthcore.domain.PasswordConfirmationForm.getPassword(), it.unitn.healthcore.domain.EmployeeRegistrationForm.getSurname(), and it.unitn.healthcore.domain.Department.getTotalStaffPositions().
Referenced by it.unitn.healthcore.business.UserService.registerEmployee().
registerEmployee()
void it.unitn.healthcore.business.UserService.registerEmployee (EmployeeRegistrationForm user)
Registers a new employee (doctor or administrator) in the system.
This method validates the employee's registration form and determines the role of the employee (Doctor or Administrator). It calls the appropriate registration method (registerDoctor() or registerAdministrator()) based on the role. If the role is not valid, it throws a ResponseStatusException with a 400 BAD REQUEST status.
Parameters
user The EmployeeRegistrationForm object containing the employee's registration details.
Exceptions
ResponseStatusException if the role is not valid or if any other validation fails.
Definition at line 183 of file UserService.java.
References it.unitn.healthcore.domain.EmployeeRegistrationForm.getRole(), it.unitn.healthcore.domain.PasswordConfirmationForm.isValidPasswordForm(), it.unitn.healthcore.business.UserService.registerAdministrator(), and it.unitn.healthcore.business.UserService.registerDoctor().
Referenced by it.unitn.healthcore.controller.UserController.addEmployee().
registerPatient()
void it.unitn.healthcore.business.UserService.registerPatient (PatientRegistrationForm user)
Registers a new patient in the system.
This method validates the patient's registration form, checks if the healthcare card number is valid and unique, and then creates a new Patient object. It calls the registerUser() method to save the new patient to the database. If any validation fails, it throws a ResponseStatusException with an appropriate status code and message.
Parameters
user The PatientRegistrationForm object containing the patient's registration details.
Exceptions
ResponseStatusException if the healthcare card number is invalid or already exists, or if any other validation fails.
Definition at line 161 of file UserService.java.
References it.unitn.healthcore.persistence.PatientRepository.existsByHealthcareCardNumber(), it.unitn.healthcore.domain.PasswordConfirmationForm.getEmail(), it.unitn.healthcore.domain.PatientRegistrationForm.getHealthcareCardNumber(), it.unitn.healthcore.domain.PatientRegistrationForm.getName(), it.unitn.healthcore.domain.PasswordConfirmationForm.getPassword(), it.unitn.healthcore.domain.PatientRegistrationForm.getSurname(), and it.unitn.healthcore.domain.PasswordConfirmationForm.isValidPasswordForm().
Referenced by it.unitn.healthcore.controller.UserController.addPatient().
sendOtp()
void it.unitn.healthcore.business.UserService.sendOtp (String email)
Sends an OTP (One-Time Password) to the specified email address for user authentication or password recovery.
This method checks if a user with the provided email exists in the database. If the user is found, it simulates sending an OTP to the user's email. In a real-world application, this method would include logic to generate a unique OTP and send it via email using an email service. If no user is found with the provided email, it throws a ResponseStatusException with a 404 NOT FOUND status.
Parameters
email The email address to which the OTP should be sent.
Exceptions
ResponseStatusException if no user is found with the provided email.
Definition at line 95 of file UserService.java.
References it.unitn.healthcore.persistence.UserRepository.findUserByEmail().
Referenced by it.unitn.healthcore.controller.UserController.requestPasswordRecovery().
updateUserProfile()
void it.unitn.healthcore.business.UserService.updateUserProfile (ProfileUpdateForm form)
Updates the profile of the currently authenticated user based on the provided object .
This method retrieves the currently authenticated user and updates their profile information (name, surname, email, password, and specialization) based on the provided ProfileUpdateForm. It performs various checks to ensure that the new values are valid and different from the existing values. If any validation fails, it throws a ResponseStatusException with an appropriate status code and message. After updating the user's profile, it refreshes the security context to reflect the changes in the user's authentication details.
Parameters
form The ProfileUpdateForm object containing the updated profile information.
Exceptions
ResponseStatusException if any validation checks fail (e.g., email already taken, invalid specialization).
Definition at line 281 of file UserService.java.
References it.unitn.healthcore.persistence.UserRepository.findUserByEmail(), it.unitn.healthcore.business.UserService.getCurrentUser(), it.unitn.healthcore.domain.PasswordConfirmationForm.getEmail(), it.unitn.healthcore.domain.User.getEmail(), it.unitn.healthcore.domain.ProfileUpdateForm.getName(), it.unitn.healthcore.domain.User.getName(), it.unitn.healthcore.domain.PasswordConfirmationForm.getPassword(), it.unitn.healthcore.domain.PasswordConfirmationForm.getPasswordConfirmation(), it.unitn.healthcore.domain.ProfileUpdateForm.getSpecialization(), it.unitn.healthcore.domain.ProfileUpdateForm.getSurname(), it.unitn.healthcore.domain.User.getSurname(), it.unitn.healthcore.business.UserService.recoverPassword(), it.unitn.healthcore.domain.User.setEmail(), it.unitn.healthcore.domain.User.setName(), and it.unitn.healthcore.domain.User.setSurname().
Referenced by it.unitn.healthcore.controller.UserController.updateProfile().
verifyOtp()
Boolean it.unitn.healthcore.business.UserService.verifyOtp (String otp)
Verifies the provided OTP (One-Time Password) for user authentication or password recovery.
This method checks if the provided OTP matches a predefined value (in this case, "123456"). If the OTP is correct, it sets the otpVerified flag to true and returns true; otherwise, it returns false. In a real-world application, this method would include logic to verify the OTP against a generated value sent to the user's email or phone.
Parameters
otp The OTP provided by the user for verification.
Returns
A boolean indicating whether the OTP is valid (true) or invalid (false).
Definition at line 78 of file UserService.java.
Referenced by it.unitn.healthcore.controller.UserController.verifyOtp(), and it.unitn.healthcore.controller.UserController.verifyRecoveryOtp().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/business/UserService.java