HealthCore: it.unitn.healthcore.controller.UserController Class Reference
it.unitn.healthcore.controller.UserController Class Reference
This class serves as a REST controller for handling user-related operations such as registration, profile updates, password recovery, and OTP verification.
Public Member Functions
UserController (UserService userService)
Constructor for UserController, which is autowired with the UserService to handle business logic related to user operations.
ResponseEntity< Void > addPatient (@RequestBody PatientRegistrationForm user)
ResponseEntity< Void > addEmployee (@RequestBody EmployeeRegistrationForm user)
String otpPage ()
get the OTP verification page.
ResponseEntity< Void > verifyOtp (@RequestParam String code)
verify the OTP code sent to the user's email.
String userHomepage (@RequestParam(required=false) String message)
display the user's homepage after successful login and OTP verification.
ResponseEntity< Void > deleteAccount ()
delete the current user's account and redirect to the login page.
String requestPasswordRecovery (@RequestParam String email)
handle the password recovery request by sending an OTP to the user's email and redirecting to the OTP verification page.
String verifyRecoveryOtp (@RequestParam String otp)
handle the password recovery request by sending an OTP to the user's email and redirecting to the OTP verification page.
ResponseEntity< Void > recoverPassword (@RequestBody PasswordConfirmationForm request)
handle the password recovery request by sending an OTP to the user's email and redirecting to the OTP verification page.
ResponseEntity< Void > updateProfile (@RequestBody ProfileUpdateForm profileUpdateForm)
handle the profile update request by updating the user's profile information and redirecting to the profile view page.
User viewProfile ()
Retrieves the profile information of the currently authenticated user.
Detailed Description
This class serves as a REST controller for handling user-related operations such as registration, profile updates, password recovery, and OTP verification.
This class serves as a base for specific user roles like Patient, Doctor, and Administrator. It uses JPA annotations for ORM mapping to the "users" table in the database.
See also
it.unitn.healthcore.business.UserService
Author
HealthCore Team
Version
1.0.0
Date
2026-06-11
Definition at line 25 of file UserController.java.
Constructor & Destructor Documentation
UserController()
it.unitn.healthcore.controller.UserController.UserController (UserService userService)
Constructor for UserController, which is autowired with the UserService to handle business logic related to user operations.
Parameters
userService The service that provides user-related functionalities such as registration, profile updates, password recovery, and OTP verification. @detail
Definition at line 33 of file UserController.java.
Member Function Documentation
addEmployee()
ResponseEntity<Void> it.unitn.healthcore.controller.UserController.addEmployee (@RequestBody EmployeeRegistrationForm user)
Parameters
EmployeeRegistrationForm The form containing the necessary information for registering a new employee user (e.g., doctor or administrator). @detail The service that provides user-related functionalities such as registration, profile updates, password recovery, and OTP verification.
Definition at line 58 of file UserController.java.
References it.unitn.healthcore.business.UserService.registerEmployee().
addPatient()
ResponseEntity<Void> it.unitn.healthcore.controller.UserController.addPatient (@RequestBody PatientRegistrationForm user)
Parameters
PatientRegistrationForm The form containing the necessary information for registering a new patient user. @detail The service that provides user-related functionalities such as registration, profile updates, password recovery, and OTP verification.
Definition at line 43 of file UserController.java.
References it.unitn.healthcore.business.UserService.registerPatient().
deleteAccount()
ResponseEntity<Void> it.unitn.healthcore.controller.UserController.deleteAccount ()
delete the current user's account and redirect to the login page.
Parameters
userId The ID of the user whose account is to be deleted.
Returns
A ResponseEntity that redirects the user to the login page after successfully deleting their account.
Definition at line 114 of file UserController.java.
References it.unitn.healthcore.business.UserService.deleteUser(), it.unitn.healthcore.business.UserService.getCurrentUser(), and it.unitn.healthcore.domain.User.getId().
otpPage()
String it.unitn.healthcore.controller.UserController.otpPage ()
get the OTP verification page.
Definition at line 70 of file UserController.java.
recoverPassword()
ResponseEntity<Void> it.unitn.healthcore.controller.UserController.recoverPassword (@RequestBody PasswordConfirmationForm request)
handle the password recovery request by sending an OTP to the user's email and redirecting to the OTP verification page.
Parameters
PasswordConfirmationForm The form containing the new password and its confirmation for the password recovery process.
Returns
A ResponseEntity that redirects the user to the login page after successfully updating their password.
Definition at line 153 of file UserController.java.
References it.unitn.healthcore.business.UserService.recoverPassword().
requestPasswordRecovery()
String it.unitn.healthcore.controller.UserController.requestPasswordRecovery (@RequestParam String email)
handle the password recovery request by sending an OTP to the user's email and redirecting to the OTP verification page.
Parameters
email The email address of the user requesting password recovery.
Returns
A ResponseEntity that redirects the user to the OTP verification page after sending the OTP to their email.
Definition at line 127 of file UserController.java.
References it.unitn.healthcore.business.UserService.sendOtp().
updateProfile()
ResponseEntity<Void> it.unitn.healthcore.controller.UserController.updateProfile (@RequestBody ProfileUpdateForm profileUpdateForm)
handle the profile update request by updating the user's profile information and redirecting to the profile view page.
Parameters
ProfileUpdateForm The form containing the updated profile information for the user.
Returns
A ResponseEntity that redirects the user to the profile view page after successfully updating their profile information.
Definition at line 167 of file UserController.java.
References it.unitn.healthcore.business.UserService.updateUserProfile().
userHomepage()
String it.unitn.healthcore.controller.UserController.userHomepage (@RequestParam(required=false) String message)
display the user's homepage after successful login and OTP verification.
Parameters
code The OTP code entered by the user for verification.
Returns
A string message welcoming the user to their homepage, along with any additional messages passed as query parameters.
Definition at line 98 of file UserController.java.
References it.unitn.healthcore.business.UserService.getCurrentUser(), and it.unitn.healthcore.domain.User.getName().
verifyOtp()
ResponseEntity<Void> it.unitn.healthcore.controller.UserController.verifyOtp (@RequestParam String code)
verify the OTP code sent to the user's email.
Parameters
code The OTP code entered by the user for verification.
Returns
A ResponseEntity that redirects the user to the homepage if the OTP is successfully verified, or back to the OTP page if verification fails.
Definition at line 80 of file UserController.java.
References it.unitn.healthcore.business.UserService.verifyOtp().
verifyRecoveryOtp()
String it.unitn.healthcore.controller.UserController.verifyRecoveryOtp (@RequestParam String otp)
handle the password recovery request by sending an OTP to the user's email and redirecting to the OTP verification page.
Parameters
otp The OTP code entered by the user for verification during the password recovery process.
Returns
String message indicating OTP veridcation status.
Definition at line 139 of file UserController.java.
References it.unitn.healthcore.business.UserService.verifyOtp().
viewProfile()
User it.unitn.healthcore.controller.UserController.viewProfile ()
Retrieves the profile information of the currently authenticated user.
This endpoint is accessible to all authenticated users. It returns a User object containing the details of the current user, such as name, surname, and email.
Returns
A User object with the current user's profile information.
Definition at line 180 of file UserController.java.
References it.unitn.healthcore.business.UserService.getCurrentUser().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/controller/UserController.java