HealthCore: it.unitn.healthcore.domain.Hospital Class Reference
it.unitn.healthcore.domain.Hospital Class Reference
Entity representing a hospital, mapped to the "hospitals" table.
Public Member Functions
Hospital ()
Default constructor required by JPA.
Hospital (String name, String address, String phoneNumber)
Creates a Hospital with basic contact information.
List< Department > getDepartmentList ()
Returns the hospital ID.
void setDepartmentList (List< Department > departmentList)
Returns the hospital ID.
List< InsurancePlan > getInsurancePlans ()
Returns the list of insurance plans associated with the hospital.
void setInsurancePlans (List< InsurancePlan > insurancePlans)
Sets the list of insurance plans associated with the hospital.
Integer getHospitalId ()
Returns the hospital ID.
void setHospitalId (Integer hospitalId)
Sets the hospital ID.
String getName ()
Returns the hospital name.
void setName (String name)
Sets the hospital name.
String getAddress ()
Returns the hospital address.
void setAddress (String address)
Sets the hospital address.
String getPhoneNumber ()
Returns the hospital phone number.
void setPhoneNumber (String phoneNumber)
Sets the hospital phone number.
Detailed Description
Entity representing a hospital, mapped to the "hospitals" table.
Holds contact details and maintains relationships with Departments and InsurancePlans.
Author
HealthCore Team
Version
1.0.0
Date
2026-06-12
Definition at line 18 of file Hospital.java.
Constructor & Destructor Documentation
Hospital() [1/2]
it.unitn.healthcore.domain.Hospital.Hospital ()
Default constructor required by JPA.
Definition at line 31 of file Hospital.java.
Hospital() [2/2]
it.unitn.healthcore.domain.Hospital.Hospital (String name, String address, String phoneNumber)
Creates a Hospital with basic contact information.
Parameters
name The hospital name.
address The hospital address.
phoneNumber The hospital phone number.
Definition at line 39 of file Hospital.java.
Member Function Documentation
getAddress()
String it.unitn.healthcore.domain.Hospital.getAddress ()
Returns the hospital address.
Definition at line 86 of file Hospital.java.
getDepartmentList()
List<Department> it.unitn.healthcore.domain.Hospital.getDepartmentList ()
Returns the hospital ID.
Definition at line 46 of file Hospital.java.
getHospitalId()
Integer it.unitn.healthcore.domain.Hospital.getHospitalId ()
Returns the hospital ID.
Definition at line 66 of file Hospital.java.
Referenced by it.unitn.healthcore.domain.InsurancePlan.isCoveredAtHospital().
getInsurancePlans()
List<InsurancePlan> it.unitn.healthcore.domain.Hospital.getInsurancePlans ()
Returns the list of insurance plans associated with the hospital.
Definition at line 56 of file Hospital.java.
getName()
String it.unitn.healthcore.domain.Hospital.getName ()
Returns the hospital name.
Definition at line 76 of file Hospital.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), and it.unitn.healthcore.business.PatientService.getDoctorDescription().
getPhoneNumber()
String it.unitn.healthcore.domain.Hospital.getPhoneNumber ()
Returns the hospital phone number.
Definition at line 96 of file Hospital.java.
setAddress()
void it.unitn.healthcore.domain.Hospital.setAddress (String address)
Sets the hospital address.
Definition at line 91 of file Hospital.java.
setDepartmentList()
void it.unitn.healthcore.domain.Hospital.setDepartmentList (List< Department > departmentList)
Returns the hospital ID.
Definition at line 51 of file Hospital.java.
setHospitalId()
void it.unitn.healthcore.domain.Hospital.setHospitalId (Integer hospitalId)
Sets the hospital ID.
Definition at line 71 of file Hospital.java.
setInsurancePlans()
void it.unitn.healthcore.domain.Hospital.setInsurancePlans (List< InsurancePlan > insurancePlans)
Sets the list of insurance plans associated with the hospital.
Definition at line 61 of file Hospital.java.
setName()
void it.unitn.healthcore.domain.Hospital.setName (String name)
Sets the hospital name.
Definition at line 81 of file Hospital.java.
setPhoneNumber()
void it.unitn.healthcore.domain.Hospital.setPhoneNumber (String phoneNumber)
Sets the hospital phone number.
Definition at line 101 of file Hospital.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/Hospital.java