HealthCore: it.unitn.healthcore.domain.PasswordConfirmationForm Class Reference
it.unitn.healthcore.domain.PasswordConfirmationForm Class Reference
This class serves as a base form for user registration processes that require password confirmation.
Public Member Functions
PasswordConfirmationForm ()
Default constructor required by JPA.
PasswordConfirmationForm (String email, String password, String passwordConfirmation)
Creates a PasswordConfirmationForm with the specified email, password, and password confirmation.
void isValidPasswordForm ()
Validates the password confirmation form by checking if the password and confirmation match, if the password meets security requirements, and if the email is valid.
String getEmail ()
Email getter.
void setEmail (String email)
Email setter.
String getPassword ()
Password getter.
void setPassword (String password)
Password setter.
String getPasswordConfirmation ()
Password confirmation getter.
void setPasswordConfirmation (String passwordConfirmation)
Password confirmation setter.
Detailed Description
This class serves as a base form for user registration processes that require password confirmation.
Author
HealthCore Team
Version
1.0.0
Date
2026-06-12
Definition at line 15 of file PasswordConfirmationForm.java.
Constructor & Destructor Documentation
PasswordConfirmationForm() [1/2]
it.unitn.healthcore.domain.PasswordConfirmationForm.PasswordConfirmationForm ()
Default constructor required by JPA.
Definition at line 20 of file PasswordConfirmationForm.java.
PasswordConfirmationForm() [2/2]
it.unitn.healthcore.domain.PasswordConfirmationForm.PasswordConfirmationForm (String email, String password, String passwordConfirmation)
Creates a PasswordConfirmationForm with the specified email, password, and password confirmation.
Definition at line 23 of file PasswordConfirmationForm.java.
Member Function Documentation
getEmail()
String it.unitn.healthcore.domain.PasswordConfirmationForm.getEmail ()
Email getter.
Definition at line 91 of file PasswordConfirmationForm.java.
Referenced by it.unitn.healthcore.business.UserService.recoverPassword(), it.unitn.healthcore.business.UserService.registerAdministrator(), it.unitn.healthcore.business.UserService.registerDoctor(), it.unitn.healthcore.business.UserService.registerPatient(), and it.unitn.healthcore.business.UserService.updateUserProfile().
getPassword()
String it.unitn.healthcore.domain.PasswordConfirmationForm.getPassword ()
Password getter.
Definition at line 101 of file PasswordConfirmationForm.java.
Referenced by it.unitn.healthcore.domain.PasswordConfirmationForm.isValidPasswordForm(), it.unitn.healthcore.business.UserService.recoverPassword(), it.unitn.healthcore.business.UserService.registerAdministrator(), it.unitn.healthcore.business.UserService.registerDoctor(), it.unitn.healthcore.business.UserService.registerPatient(), and it.unitn.healthcore.business.UserService.updateUserProfile().
getPasswordConfirmation()
String it.unitn.healthcore.domain.PasswordConfirmationForm.getPasswordConfirmation ()
Password confirmation getter.
Definition at line 111 of file PasswordConfirmationForm.java.
Referenced by it.unitn.healthcore.domain.PasswordConfirmationForm.isValidPasswordForm(), and it.unitn.healthcore.business.UserService.updateUserProfile().
isValidPasswordForm()
void it.unitn.healthcore.domain.PasswordConfirmationForm.isValidPasswordForm ()
Validates the password confirmation form by checking if the password and confirmation match, if the password meets security requirements, and if the email is valid.
If any validation fails, it throws a ResponseStatusException with an appropriate HTTP status code and message indicating the reason for the failure.
Definition at line 65 of file PasswordConfirmationForm.java.
References it.unitn.healthcore.domain.PasswordConfirmationForm.getPassword(), and it.unitn.healthcore.domain.PasswordConfirmationForm.getPasswordConfirmation().
Referenced by it.unitn.healthcore.business.UserService.recoverPassword(), it.unitn.healthcore.business.UserService.registerEmployee(), and it.unitn.healthcore.business.UserService.registerPatient().
setEmail()
void it.unitn.healthcore.domain.PasswordConfirmationForm.setEmail (String email)
Email setter.
Definition at line 96 of file PasswordConfirmationForm.java.
setPassword()
void it.unitn.healthcore.domain.PasswordConfirmationForm.setPassword (String password)
Password setter.
Definition at line 106 of file PasswordConfirmationForm.java.
setPasswordConfirmation()
void it.unitn.healthcore.domain.PasswordConfirmationForm.setPasswordConfirmation (String passwordConfirmation)
Password confirmation setter.
Definition at line 116 of file PasswordConfirmationForm.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/PasswordConfirmationForm.java