HealthCore: it.unitn.healthcore.business.PatientService Class Reference
it.unitn.healthcore.business.PatientService Class Reference
PatientService is a service class that provides business logic related to patient management.
Public Member Functions
PatientService (InsurancePlanRepository insurancePlanRepository, UserService userService, DoctorRepository doctorRepository, AppointmentRepository appointmentRepository)
Constructor for the PatientService class.
void updateInsurancePlan (Integer planId)
Updates the insurance plan for the currently authenticated patient.
InsurancePlan getCurrentInsurancePlan ()
Retrieves the current insurance plan for the authenticated patient.
String getDoctorDescription (Integer doctorId)
Retrieves detailed information about a doctor based on their ID.
Appointment bookAppointment (Integer doctorId, LocalDateTime start, LocalDateTime end)
Books an appointment with a specified doctor for the currently authenticated patient.
void modifyAppointment (Integer appointmentId, LocalDateTime startTime, LocalDateTime endTime)
Modifies an existing appointment for the currently authenticated patient.
void cancelAppointment (Integer appointmentId)
Cancels an existing appointment for the currently authenticated patient.
Detailed Description
PatientService is a service class that provides business logic related to patient management.
It interacts with the InsurancePlanRepository, UserService, DoctorRepository, and AppointmentRepository to perform operations related to patient insurance plans, doctor information retrieval, and appointment booking. @detail This service class contains methods for updating a patient's insurance plan, retrieving the current insurance plan, getting detailed information about a doctor, and booking appointments with doctors. It serves as an intermediary between the controller layer and the persistence layer, ensuring that business rules are applied when accessing patient-related data and performing operations.
See also
InsurancePlanRepository
UserService
DoctorRepository
AppointmentRepository
Author
HealthCore Team
Version
1.0.0
Date
2026-06-12
Definition at line 31 of file PatientService.java.
Constructor & Destructor Documentation
PatientService()
it.unitn.healthcore.business.PatientService.PatientService (InsurancePlanRepository insurancePlanRepository, UserService userService, DoctorRepository doctorRepository, AppointmentRepository appointmentRepository)
Constructor for the PatientService class.
This constructor is used to inject the dependencies of the PatientService class, including the InsurancePlan Repository, UserService, DoctorRepository, and AppointmentRepository. The @Autowired annotation allows Spring to automatically wire these dependencies when creating an instance of the PatientService.
Parameters
insurancePlanRepository The repository that provides access to insurance plan data in the database.
userService The service that provides business logic related to user management and authentication.
doctorRepository The repository that provides access to doctor data in the database.
appointmentRepository The repository that provides access to appointment data in the database.
Definition at line 44 of file PatientService.java.
Member Function Documentation
bookAppointment()
Appointment it.unitn.healthcore.business.PatientService.bookAppointment (Integer doctorId, LocalDateTime start, LocalDateTime end)
Books an appointment with a specified doctor for the currently authenticated patient.
This method takes a doctor ID, start time, and end time as input to book an appointment. It performs several checks to ensure that the appointment can be booked, including validating the time intervals, checking the doctor's availability during their shifts, verifying that there are available beds in the department, and confirming insurance coverage or processing payment if necessary. If all checks pass, it creates a new Appointment entity and saves it to the database.
Parameters
doctorId The ID of the doctor with whom to book the appointment.
start The start date and time of the appointment.
end The end date and time of the appointment.
Returns
The Appointment object representing the booked appointment.
Exceptions
ResponseStatusException if any of the checks fail (e.g., invalid time intervals, doctor not available, no beds available, payment failure) or if there is an issue with booking the appointment.
Steps to book an appointment:
Validate that the start time is before the end time.
Check if the doctor exists.
Check if the requested time is during the doctor's shift.
Check for overlapping appointments for the doctor.
Check bed availability in the department.
Check insurance coverage or process payment if necessary.
Create and save the appointment.
Definition at line 172 of file PatientService.java.
References it.unitn.healthcore.business.UserService.getCurrentUser(), it.unitn.healthcore.domain.Doctor.getDepartment(), it.unitn.healthcore.domain.Department.getHospital(), it.unitn.healthcore.domain.Patient.getInsurancePlan(), and it.unitn.healthcore.domain.InsurancePlan.isCoveredAtHospital().
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment().
cancelAppointment()
void it.unitn.healthcore.business.PatientService.cancelAppointment (Integer appointmentId)
Cancels an existing appointment for the currently authenticated patient.
This method takes an appointment ID as input and cancels the corresponding appointment. It first retrieves the appointment based on the provided ID and checks if it belongs to the currently authenticated patient. If the appointment does not belong to the patient, it throws a ResponseStatusException with a 403 FORBIDDEN status. If the appointment is valid for cancellation, it checks if the cancellation is happening more than 24 hours before the appointment start time. If so, it processes a refund for the patient. Finally, it deletes the appointment from the database.
Parameters
appointmentId The ID of the appointment to be canceled.
Exceptions
ResponseStatusException if any of the checks fail (e.g., appointment not found, not assigned to patient) or if there is an issue with canceling the appointment.
Definition at line 364 of file PatientService.java.
References it.unitn.healthcore.business.UserService.getCurrentUser(), it.unitn.healthcore.domain.User.getId(), it.unitn.healthcore.domain.Appointment.getPatient(), and it.unitn.healthcore.domain.Appointment.getStartTime().
Referenced by it.unitn.healthcore.controller.PatientController.cancelAppointment().
getCurrentInsurancePlan()
InsurancePlan it.unitn.healthcore.business.PatientService.getCurrentInsurancePlan ()
Retrieves the current insurance plan for the authenticated patient.
This method retrieves the currently authenticated patient from the UserService and returns their associated insurance plan. If the patient does not have an insurance plan, it may return null or an appropriate response based on the application's requirements.
Returns
The InsurancePlan object representing the current insurance plan of the authenticated patient, or null if the patient does not have an insurance plan.
Exceptions
ResponseStatusException if there is an issue retrieving the current patient's information or if the user is not authenticated as a patient.
Definition at line 91 of file PatientService.java.
References it.unitn.healthcore.business.UserService.getCurrentUser(), and it.unitn.healthcore.domain.Patient.getInsurancePlan().
Referenced by it.unitn.healthcore.controller.PatientController.updateInsurancePlan().
getDoctorDescription()
String it.unitn.healthcore.business.PatientService.getDoctorDescription (Integer doctorId)
Retrieves detailed information about a doctor based on their ID.
This method takes a doctor ID as input and retrieves the corresponding Doctor entity from the DoctorRepository. If the doctor is not found, it throws a ResponseStatusException with a 404 NOT FOUND status. If the doctor is found, it constructs a string containing detailed information about the doctor, including their name, surname, email, specialization, department, hospital, appointment price, and shift schedule. The method returns this string as the output.
Parameters
doctorId The ID of the doctor for whom to retrieve detailed information.
Returns
A string containing detailed information about the specified doctor.
Exceptions
ResponseStatusException if the doctor with the specified ID is not found in the database.
Definition at line 104 of file PatientService.java.
References it.unitn.healthcore.domain.Doctor.getAppointmentPrice(), it.unitn.healthcore.domain.Doctor.getDepartment(), it.unitn.healthcore.domain.User.getEmail(), it.unitn.healthcore.domain.Department.getHospital(), it.unitn.healthcore.domain.Department.getName(), it.unitn.healthcore.domain.Hospital.getName(), it.unitn.healthcore.domain.User.getName(), it.unitn.healthcore.domain.Doctor.getShifts(), it.unitn.healthcore.domain.Doctor.getSpecialization(), and it.unitn.healthcore.domain.User.getSurname().
Referenced by it.unitn.healthcore.controller.PatientController.getDoctorDescription().
modifyAppointment()
void it.unitn.healthcore.business.PatientService.modifyAppointment (Integer appointmentId, LocalDateTime startTime, LocalDateTime endTime)
Modifies an existing appointment for the currently authenticated patient.
This method takes an appointment ID, new start time, and new end time as input to modify an existing appointment. It first retrieves the appointment based on the provided ID and checks if it belongs to the currently authenticated patient. It also checks if the appointment has not already started. If these checks pass, it validates the new appointment details (e.g., time intervals, doctor's availability, bed availability) and updates the appointment with the new start and end times before saving it to the database.
Parameters
appointmentId The ID of the appointment to be modified.
start The new start date and time of the appointment.
end The new end date and time of the appointment.
Exceptions
ResponseStatusException if any of the checks fail (e.g., appointment not found, not assigned to patient, appointment already started, invalid time intervals, doctor not available, no beds available) or if there is an issue with modifying the appointment.
Definition at line 225 of file PatientService.java.
References it.unitn.healthcore.business.UserService.getCurrentUser(), it.unitn.healthcore.domain.Appointment.getDoctor(), it.unitn.healthcore.domain.User.getId(), it.unitn.healthcore.domain.Appointment.getPatient(), it.unitn.healthcore.domain.Appointment.getStartTime(), it.unitn.healthcore.domain.Appointment.setEndTime(), and it.unitn.healthcore.domain.Appointment.setStartTime().
Referenced by it.unitn.healthcore.controller.PatientController.modifyAppointment().
updateInsurancePlan()
void it.unitn.healthcore.business.PatientService.updateInsurancePlan (Integer planId)
Updates the insurance plan for the currently authenticated patient.
This method takes an insurance plan ID as input and updates the insurance plan for the currently authenticated patient. It first checks if the specified insurance plan exists in the database. If it does not exist, it throws a ResponseStatusException with a 404 NOT FOUND status. If the insurance plan exists, it retrieves the current patient from the UserService and validates whether the patient can subscribe to the specified insurance plan. If the validation is successful, it updates the patient's insurance plan with the new plan.
Parameters
planId The ID of the insurance plan to update for the current patient.
Exceptions
ResponseStatusException if the specified insurance plan does not exist or if there is an issue with updating the patient's insurance plan.
Definition at line 59 of file PatientService.java.
References it.unitn.healthcore.business.UserService.getCurrentUser(), it.unitn.healthcore.domain.User.getId(), and it.unitn.healthcore.domain.Patient.setInsurancePlan().
Referenced by it.unitn.healthcore.controller.PatientController.updateInsurancePlan().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/business/PatientService.java