HealthCore: it.unitn.healthcore.domain.User Class Reference
it.unitn.healthcore.domain.User Class Reference
Represents a general user in our system.
Public Member Functions
User ()
Default constructor required by JPA.
User (String name, String surname, String email, String password)
Creates a User with full credentials.
Integer getId ()
Returns a string representation of the User.
void setId (Integer id)
Sets the user ID.
String getName ()
Returns the first name of the user.
void setName (String name)
Sets the first name of the user.
String getSurname ()
Returns the last name of the user.
void setSurname (String surname)
Sets the last name of the user.
String getEmail ()
Returns the email address of the user.
void setEmail (String email)
Sets the email address of the user.
String getPassword ()
Returns the password of the user.
void setPassword (String password)
Sets the password of the user.
Detailed Description
Represents a general user in our system.
This class serves as a base for specific user roles like Patient, Doctor, and Administrator. It uses JPA annotations for ORM mapping to the "users" table in the database.
Author
HealthCore Team
Version
1.0.0
Date
2026-06-11
Definition at line 19 of file User.java.
Constructor & Destructor Documentation
User() [1/2]
it.unitn.healthcore.domain.User.User ()
Default constructor required by JPA.
Definition at line 37 of file User.java.
User() [2/2]
it.unitn.healthcore.domain.User.User (String name, String surname, String email, String password)
Creates a User with full credentials.
Parameters
name First name.
surname Last name.
email Email address.
password Account password.
Definition at line 47 of file User.java.
Member Function Documentation
getEmail()
String it.unitn.healthcore.domain.User.getEmail ()
Returns the email address of the user.
Definition at line 78 of file User.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), it.unitn.healthcore.business.PatientService.getDoctorDescription(), it.unitn.healthcore.domain.SecurityUser.getUsername(), and it.unitn.healthcore.business.UserService.updateUserProfile().
getId()
Integer it.unitn.healthcore.domain.User.getId ()
Returns a string representation of the User.
Definition at line 54 of file User.java.
Referenced by it.unitn.healthcore.business.PatientService.cancelAppointment(), it.unitn.healthcore.controller.UserController.deleteAccount(), it.unitn.healthcore.business.AppointmentService.getAppointmentDetails(), it.unitn.healthcore.business.PatientService.modifyAppointment(), and it.unitn.healthcore.business.PatientService.updateInsurancePlan().
getName()
String it.unitn.healthcore.domain.User.getName ()
Returns the first name of the user.
Definition at line 62 of file User.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), it.unitn.healthcore.business.PatientService.getDoctorDescription(), it.unitn.healthcore.business.UserService.updateUserProfile(), and it.unitn.healthcore.controller.UserController.userHomepage().
getPassword()
String it.unitn.healthcore.domain.User.getPassword ()
Returns the password of the user.
Definition at line 86 of file User.java.
Referenced by it.unitn.healthcore.domain.SecurityUser.getPassword().
getSurname()
String it.unitn.healthcore.domain.User.getSurname ()
Returns the last name of the user.
Definition at line 70 of file User.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), it.unitn.healthcore.business.PatientService.getDoctorDescription(), and it.unitn.healthcore.business.UserService.updateUserProfile().
setEmail()
void it.unitn.healthcore.domain.User.setEmail (String email)
Sets the email address of the user.
Definition at line 82 of file User.java.
Referenced by it.unitn.healthcore.business.UserService.updateUserProfile().
setId()
void it.unitn.healthcore.domain.User.setId (Integer id)
Sets the user ID.
Definition at line 58 of file User.java.
setName()
void it.unitn.healthcore.domain.User.setName (String name)
Sets the first name of the user.
Definition at line 66 of file User.java.
Referenced by it.unitn.healthcore.business.UserService.updateUserProfile().
setPassword()
void it.unitn.healthcore.domain.User.setPassword (String password)
Sets the password of the user.
Definition at line 90 of file User.java.
Referenced by it.unitn.healthcore.business.UserService.recoverPassword().
setSurname()
void it.unitn.healthcore.domain.User.setSurname (String surname)
Sets the last name of the user.
Definition at line 74 of file User.java.
Referenced by it.unitn.healthcore.business.UserService.updateUserProfile().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/User.java