HealthCore: it.unitn.healthcore.business.DoctorService Class Reference
it.unitn.healthcore.business.DoctorService Class Reference
DoctorService is a service class that provides business logic related to doctor management and scheduling.
Public Member Functions
DoctorService (DoctorRepository doctorRepository, ShiftRepository shiftRepository, UserService userService, DepartmentRepository departmentRepository)
Constructor for the DoctorService class.
List< Doctor > getAllDoctors ()
Retrieves a list of all doctors in the system.
Doctor findDoctor (Integer id)
Retrieves detailed information about a specific doctor based on the doctor ID.
void addShift (Integer id, LocalDateTime startTime, LocalDateTime endTime)
Helper method to retrieve detailed information about a doctor associated with a specific appointment.
void deleteShift (Integer shiftId)
Helper method to delete a specific shift based on its ID.
void modifyShift (Integer shiftId, LocalDateTime startTime, LocalDateTime endTime)
Helper method to retrieve detailed information about a doctor associated with a specific appointment.
List< Shift > getCurrentDoctorShifts ()
Retrieves the shifts of the currently authenticated doctor.
List< Department > getAvailableDepartments ()
Retrieves a list of departments that have available staff positions for new doctors.
void changeDepartment (Integer doctorId, Integer departmentId)
Changes the department of a doctor to a new department.
Detailed Description
DoctorService is a service class that provides business logic related to doctor management and scheduling.
It interacts with the DoctorRepository, ShiftRepository, UserService, and AppointmentRepository to perform operations such as retrieving doctor information, managing shifts, and handling appointments. The service ensures that doctors' schedules adhere to constraints such as maximum weekly hours and non-overlapping shifts.
See also
DoctorRepository
ShiftRepository
UserService
AppointmentRepository
Author
HealthCore Team
Version
1.0.0
Date
2026-06-11
Definition at line 29 of file DoctorService.java.
Constructor & Destructor Documentation
DoctorService()
it.unitn.healthcore.business.DoctorService.DoctorService (DoctorRepository doctorRepository, ShiftRepository shiftRepository, UserService userService, DepartmentRepository departmentRepository)
Constructor for the DoctorService class.
This constructor is used to inject the DoctorRepository, ShiftRepository, UserService, and AppointmentRepository dependencies into the service. The @Autowired annotation allows Spring to automatically wire the service when creating an instance of the DoctorService.
Parameters
doctorRepository The repository that provides access to doctor data in the database.
shiftRepository The repository that provides access to shift data in the database.
userService The service that provides user-related functionalities such as retrieving the current user.
departmentRepository The repository that provides access to department data in the database.
Definition at line 42 of file DoctorService.java.
Member Function Documentation
addShift()
void it.unitn.healthcore.business.DoctorService.addShift (Integer id, LocalDateTime startTime, LocalDateTime endTime)
Helper method to retrieve detailed information about a doctor associated with a specific appointment.
This method constructs a string containing the doctor's personal information, specialization, department, hospital, appointment price, shift schedule, and any notes associated with the appointment.
Parameters
appointment The appointment for which to retrieve doctor details.
Returns
A string containing detailed information about the doctor associated with the specified appointment.
Definition at line 136 of file DoctorService.java.
References it.unitn.healthcore.business.DoctorService.findDoctor(), and it.unitn.healthcore.domain.Doctor.getShifts().
Referenced by it.unitn.healthcore.controller.DoctorController.addShiftTime().
changeDepartment()
void it.unitn.healthcore.business.DoctorService.changeDepartment (Integer doctorId, Integer departmentId)
Changes the department of a doctor to a new department.
This method retrieves the doctor and the new department based on their IDs. It checks if the new department has available staff positions. If the department is full, it throws a ResponseStatusException with a 400 BAD REQUEST status. If the department has available positions, it updates the doctor's department The method is annotated with @Transactional to ensure that the changes are persisted in the database.
Parameters
doctorId The ID of the doctor whose department is to be changed.
departmentId The ID of the new department to which the doctor will be assigned.
Exceptions
ResponseStatusException if the doctor or department is not found, or if the new department has no available staff positions.
Definition at line 269 of file DoctorService.java.
References it.unitn.healthcore.domain.Department.getDoctors(), it.unitn.healthcore.domain.Department.getTotalStaffPositions(), and it.unitn.healthcore.domain.Doctor.setDepartment().
Referenced by it.unitn.healthcore.controller.DoctorController.changeDepartment().
deleteShift()
void it.unitn.healthcore.business.DoctorService.deleteShift (Integer shiftId)
Helper method to delete a specific shift based on its ID.
This method interacts with the ShiftRepository to find and delete a shift by its ID. If the shift is found, it is deleted from the database; otherwise, it throws a ResponseStatusException with a 404 NOT FOUND status.
Parameters
shiftId The ID of the shift to delete.
Exceptions
ResponseStatusException if the shift with the specified ID is not found in the database.
Definition at line 173 of file DoctorService.java.
References it.unitn.healthcore.domain.Shift.getDoctor().
Referenced by it.unitn.healthcore.controller.DoctorController.deleteShift().
findDoctor()
Doctor it.unitn.healthcore.business.DoctorService.findDoctor (Integer id)
Retrieves detailed information about a specific doctor based on the doctor ID.
This method interacts with the DoctorRepository to find a doctor by their ID. If the doctor is found, it returns the Doctor object; otherwise, it throws a ResponseStatusException with a 404 NOT FOUND status.
Parameters
id The ID of the doctor to retrieve.
Returns
The Doctor object corresponding to the specified ID.
Exceptions
ResponseStatusException if the doctor with the specified ID is not found in the database.
Definition at line 61 of file DoctorService.java.
Referenced by it.unitn.healthcore.business.DoctorService.addShift(), and it.unitn.healthcore.controller.DoctorController.viewDoctorManagementPage().
getAllDoctors()
List<Doctor> it.unitn.healthcore.business.DoctorService.getAllDoctors ()
Retrieves a list of all doctors in the system.
This method interacts with the DoctorRepository to fetch all doctor records from the database and returns them as a list.
Returns
A list of all doctors in the system.
Definition at line 52 of file DoctorService.java.
Referenced by it.unitn.healthcore.controller.DoctorController.viewDoctors().
getAvailableDepartments()
List<Department> it.unitn.healthcore.business.DoctorService.getAvailableDepartments ()
Retrieves a list of departments that have available staff positions for new doctors.
This method interacts with the DepartmentRepository to fetch all department records from the database. It then filters the list to include only those departments that have available staff positions (i.e., the number of occupied positions is less than the total staff positions). The filtered list of available departments is returned.
Returns
A list of departments that have available staff positions for new doctors.
Definition at line 245 of file DoctorService.java.
Referenced by it.unitn.healthcore.controller.DoctorController.viewAvailableDepartments().
getCurrentDoctorShifts()
List<Shift> it.unitn.healthcore.business.DoctorService.getCurrentDoctorShifts ()
Retrieves the shifts of the currently authenticated doctor.
This method uses the UserService to get the current user and checks if the user is an instance of Doctor. If so, it retrieves and returns a list of the doctor's shifts sorted by start time. If the current user is not a doctor, it throws a ResponseStatusException with a 403 FORBIDDEN status.
Returns
A list of shifts for the currently authenticated doctor, sorted by start time.
Exceptions
ResponseStatusException if the current user is not a doctor or if there is an issue retrieving the doctor information.
Definition at line 234 of file DoctorService.java.
References it.unitn.healthcore.business.UserService.getCurrentUser(), and it.unitn.healthcore.domain.Doctor.getShifts().
Referenced by it.unitn.healthcore.controller.DoctorController.viewMyShifts().
modifyShift()
void it.unitn.healthcore.business.DoctorService.modifyShift (Integer shiftId, LocalDateTime startTime, LocalDateTime endTime)
Helper method to retrieve detailed information about a doctor associated with a specific appointment.
This method constructs a string containing the doctor's personal information, specialization, department, hospital, appointment price, shift schedule, and any notes associated with the appointment.
Parameters
appointment The appointment for which to retrieve doctor details.
Returns
A string containing detailed information about the doctor associated with the specified appointment.
Definition at line 189 of file DoctorService.java.
References it.unitn.healthcore.domain.Shift.getDoctor(), it.unitn.healthcore.domain.Shift.getEndTime(), it.unitn.healthcore.domain.Doctor.getShifts(), it.unitn.healthcore.domain.Shift.getStartTime(), it.unitn.healthcore.domain.Shift.setEndTime(), and it.unitn.healthcore.domain.Shift.setStartTime().
Referenced by it.unitn.healthcore.controller.DoctorController.modifyShift().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/business/DoctorService.java