HealthCore: it.unitn.healthcore.business.AppointmentService Class Reference
it.unitn.healthcore.business.AppointmentService Class Reference
Public Member Functions
AppointmentService (UserService userService, AppointmentRepository appointmentRepository)
List< Appointment > getFutureAppointments ()
List< Appointment > getPastAppointments ()
String getAppointmentDetails (Integer appointmentId)
Detailed Description
Definition at line 15 of file AppointmentService.java.
Constructor & Destructor Documentation
AppointmentService()
it.unitn.healthcore.business.AppointmentService.AppointmentService (UserService userService, AppointmentRepository appointmentRepository)
Definition at line 20 of file AppointmentService.java.
Member Function Documentation
getAppointmentDetails()
String it.unitn.healthcore.business.AppointmentService.getAppointmentDetails (Integer appointmentId)
Definition at line 74 of file AppointmentService.java.
References it.unitn.healthcore.domain.Appointment.getAppointmentId(), it.unitn.healthcore.business.UserService.getCurrentUser(), it.unitn.healthcore.domain.Appointment.getDoctor(), it.unitn.healthcore.domain.Appointment.getEndTime(), it.unitn.healthcore.domain.User.getId(), it.unitn.healthcore.domain.Appointment.getPatient(), and it.unitn.healthcore.domain.Appointment.getStartTime().
Referenced by it.unitn.healthcore.controller.DoctorController.viewAppointmentDetail(), and it.unitn.healthcore.controller.PatientController.viewAppointmentDetail().
getFutureAppointments()
List<Appointment> it.unitn.healthcore.business.AppointmentService.getFutureAppointments ()
Definition at line 25 of file AppointmentService.java.
References it.unitn.healthcore.business.UserService.getCurrentUser().
Referenced by it.unitn.healthcore.controller.DoctorController.viewFutureAppointments(), and it.unitn.healthcore.controller.PatientController.viewFutureAppointments().
getPastAppointments()
List<Appointment> it.unitn.healthcore.business.AppointmentService.getPastAppointments ()
Definition at line 50 of file AppointmentService.java.
References it.unitn.healthcore.business.UserService.getCurrentUser().
Referenced by it.unitn.healthcore.controller.DoctorController.viewPastAppointments(), and it.unitn.healthcore.controller.PatientController.viewPastAppointments().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/business/AppointmentService.java