HealthCore: it.unitn.healthcore.domain.ProfileUpdateForm Class Reference
it.unitn.healthcore.domain.ProfileUpdateForm Class Reference
This class represents the form used for updating user profiles, extending the PasswordConfirmationForm to include additional fields such as name, surname, and specialization (for doctors).
Public Member Functions
ProfileUpdateForm ()
Default constructor required by JPA.
ProfileUpdateForm (String email, String password, String passwordConfirmation, String name, String surname, String specialization)
Creates a ProfileUpdateForm with the specified details.
ProfileUpdateForm (String email, String password, String passwordConfirmation, String name, String surname)
Creates a ProfileUpdateForm with the specified details, without specialization.
String getName ()
Name getter.
void setName (String name)
Name setter.
String getSurname ()
Surname getter.
void setSurname (String surname)
Surname setter.
String getSpecialization ()
Specialization getter.
void setSpecialization (String specialization)
Specialization setter.
Public Member Functions inherited from it.unitn.healthcore.domain.PasswordConfirmationForm
PasswordConfirmationForm ()
Default constructor required by JPA.
PasswordConfirmationForm (String email, String password, String passwordConfirmation)
Creates a PasswordConfirmationForm with the specified email, password, and password confirmation.
void isValidPasswordForm ()
Validates the password confirmation form by checking if the password and confirmation match, if the password meets security requirements, and if the email is valid.
String getEmail ()
Email getter.
void setEmail (String email)
Email setter.
String getPassword ()
Password getter.
void setPassword (String password)
Password setter.
String getPasswordConfirmation ()
Password confirmation getter.
void setPasswordConfirmation (String passwordConfirmation)
Password confirmation setter.
Detailed Description
This class represents the form used for updating user profiles, extending the PasswordConfirmationForm to include additional fields such as name, surname, and specialization (for doctors).
See also
PasswordConfirmationForm
Author
HealthCore Team
Version
1.0.0
Date
2026-06-11
Definition at line 10 of file ProfileUpdateForm.java.
Constructor & Destructor Documentation
ProfileUpdateForm() [1/3]
it.unitn.healthcore.domain.ProfileUpdateForm.ProfileUpdateForm ()
Default constructor required by JPA.
Definition at line 16 of file ProfileUpdateForm.java.
ProfileUpdateForm() [2/3]
it.unitn.healthcore.domain.ProfileUpdateForm.ProfileUpdateForm (String email, String password, String passwordConfirmation, String name, String surname, String specialization)
Creates a ProfileUpdateForm with the specified details.
Definition at line 19 of file ProfileUpdateForm.java.
ProfileUpdateForm() [3/3]
it.unitn.healthcore.domain.ProfileUpdateForm.ProfileUpdateForm (String email, String password, String passwordConfirmation, String name, String surname)
Creates a ProfileUpdateForm with the specified details, without specialization.
Definition at line 27 of file ProfileUpdateForm.java.
Member Function Documentation
getName()
String it.unitn.healthcore.domain.ProfileUpdateForm.getName ()
Name getter.
Definition at line 35 of file ProfileUpdateForm.java.
Referenced by it.unitn.healthcore.business.UserService.updateUserProfile().
getSpecialization()
String it.unitn.healthcore.domain.ProfileUpdateForm.getSpecialization ()
Specialization getter.
Definition at line 54 of file ProfileUpdateForm.java.
Referenced by it.unitn.healthcore.business.UserService.updateUserProfile().
getSurname()
String it.unitn.healthcore.domain.ProfileUpdateForm.getSurname ()
Surname getter.
Definition at line 45 of file ProfileUpdateForm.java.
Referenced by it.unitn.healthcore.business.UserService.updateUserProfile().
setName()
void it.unitn.healthcore.domain.ProfileUpdateForm.setName (String name)
Name setter.
Definition at line 40 of file ProfileUpdateForm.java.
setSpecialization()
void it.unitn.healthcore.domain.ProfileUpdateForm.setSpecialization (String specialization)
Specialization setter.
Definition at line 59 of file ProfileUpdateForm.java.
setSurname()
void it.unitn.healthcore.domain.ProfileUpdateForm.setSurname (String surname)
Surname setter.
Definition at line 49 of file ProfileUpdateForm.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/ProfileUpdateForm.java