HealthCore: it.unitn.healthcore.domain.Patient Class Reference
it.unitn.healthcore.domain.Patient Class Reference
Represents a patient in our system, extending the User class.
Public Member Functions
Patient ()
Default constructor required by JPA.
Patient (String name, String surname, String email, String password, Integer healthcare_card_number)
Creates a Patient with full credentials.
String toString ()
It creates full insurance plan including Patient.
List< Appointment > getAppointments ()
Getter for Appointment.
void setAppointments (List< Appointment > appointments)
Setter for Appointment.
Integer getHealthcareCardNumber ()
Healthcare card number getter.
void setHealthcareCardNumber (Integer healthcareCardNumber)
Healthcare card number setter.
InsurancePlan getInsurancePlan ()
Insurance plan getter.
void setInsurancePlan (InsurancePlan insurancePlan)
Insurance plan setter.
String getTriageStatus ()
Triage status getter.
void setTriageStatus (String triageStatus)
Triage status setter.
Public Member Functions inherited from it.unitn.healthcore.domain.User
User ()
Default constructor required by JPA.
User (String name, String surname, String email, String password)
Creates a User with full credentials.
Integer getId ()
Returns a string representation of the User.
void setId (Integer id)
Sets the user ID.
String getName ()
Returns the first name of the user.
void setName (String name)
Sets the first name of the user.
String getSurname ()
Returns the last name of the user.
void setSurname (String surname)
Sets the last name of the user.
String getEmail ()
Returns the email address of the user.
void setEmail (String email)
Sets the email address of the user.
String getPassword ()
Returns the password of the user.
void setPassword (String password)
Sets the password of the user.
Detailed Description
Represents a patient in our system, extending the User class.
It uses JPA annotations for ORM mapping to the "patients" table in the database.
The Patient class includes attributes specific to patients, such as healthcare card number, insurance plan, and triage status. It also maintains a one-to-many relationship with appointments, allowing us to track all appointments associated with a patient.
The triage status can be used to manage patient flow in emergency situations, indicating whether a patient is currently in triage or not.
The insurance plan association allows us to determine which insurance plan a patient has and whether it covers specific hospitals or treatments.
The healthcare card number is a unique identifier for patients, which can be used for administrative and billing purposes
Author
HealthCore Team
Version
1.0.0
Date
2026-06-12
Definition at line 22 of file Patient.java.
Constructor & Destructor Documentation
Patient() [1/2]
it.unitn.healthcore.domain.Patient.Patient ()
Default constructor required by JPA.
Definition at line 33 of file Patient.java.
Patient() [2/2]
it.unitn.healthcore.domain.Patient.Patient (String name, String surname, String email, String password, Integer healthcare_card_number)
Creates a Patient with full credentials.
Parameters
name First name.
surname Last name.
email Email address.
password Account password.
healthcare_card_number Unique healthcare card number for the patient.
Returns
A new instance of Patient with the specified attributes, with insurance plan set to null and triage status set to "NotInTriage".
Definition at line 45 of file Patient.java.
Member Function Documentation
getAppointments()
List<Appointment> it.unitn.healthcore.domain.Patient.getAppointments ()
Getter for Appointment.
Definition at line 64 of file Patient.java.
getHealthcareCardNumber()
Integer it.unitn.healthcore.domain.Patient.getHealthcareCardNumber ()
Healthcare card number getter.
Definition at line 74 of file Patient.java.
getInsurancePlan()
InsurancePlan it.unitn.healthcore.domain.Patient.getInsurancePlan ()
Insurance plan getter.
Definition at line 82 of file Patient.java.
Referenced by it.unitn.healthcore.business.PatientService.bookAppointment(), and it.unitn.healthcore.business.PatientService.getCurrentInsurancePlan().
getTriageStatus()
String it.unitn.healthcore.domain.Patient.getTriageStatus ()
Triage status getter.
Definition at line 90 of file Patient.java.
setAppointments()
void it.unitn.healthcore.domain.Patient.setAppointments (List< Appointment > appointments)
Setter for Appointment.
Definition at line 69 of file Patient.java.
setHealthcareCardNumber()
void it.unitn.healthcore.domain.Patient.setHealthcareCardNumber (Integer healthcareCardNumber)
Healthcare card number setter.
Definition at line 78 of file Patient.java.
setInsurancePlan()
void it.unitn.healthcore.domain.Patient.setInsurancePlan (InsurancePlan insurancePlan)
Insurance plan setter.
Definition at line 86 of file Patient.java.
Referenced by it.unitn.healthcore.business.PatientService.updateInsurancePlan().
setTriageStatus()
void it.unitn.healthcore.domain.Patient.setTriageStatus (String triageStatus)
Triage status setter.
Definition at line 94 of file Patient.java.
toString()
String it.unitn.healthcore.domain.Patient.toString ()
It creates full insurance plan including Patient.
Definition at line 54 of file Patient.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/Patient.java