HealthCore: it.unitn.healthcore.domain.PatientRegistrationForm Class Reference
it.unitn.healthcore.domain.PatientRegistrationForm Class Reference
This class represents the form used for patient registration, extending the PasswordConfirmationForm to include additional fields specific to patients.
Public Member Functions
PatientRegistrationForm ()
Default constructor required by JPA.
PatientRegistrationForm (String name, String surname, String email, String password, String passwordConfirmation, Integer healthcareCardNumber)
Creates a PatientRegistrationForm with the specified details.
String getName ()
Creates a PatientRegistrationForm with the specified details, without healthcare card number.
void setName (String name)
Name setter.
String getSurname ()
Surname getter.
void setSurname (String surname)
Surname setter.
Integer getHealthcareCardNumber ()
Healthcare card number getter.
void setHealthcareCardNumber (Integer healthcareCardNumber)
Healthcare card number setter.
Public Member Functions inherited from it.unitn.healthcore.domain.PasswordConfirmationForm
PasswordConfirmationForm ()
Default constructor required by JPA.
PasswordConfirmationForm (String email, String password, String passwordConfirmation)
Creates a PasswordConfirmationForm with the specified email, password, and password confirmation.
void isValidPasswordForm ()
Validates the password confirmation form by checking if the password and confirmation match, if the password meets security requirements, and if the email is valid.
String getEmail ()
Email getter.
void setEmail (String email)
Email setter.
String getPassword ()
Password getter.
void setPassword (String password)
Password setter.
String getPasswordConfirmation ()
Password confirmation getter.
void setPasswordConfirmation (String passwordConfirmation)
Password confirmation setter.
Detailed Description
This class represents the form used for patient registration, extending the PasswordConfirmationForm to include additional fields specific to patients.
See also
PasswordConfirmationForm
Author
HealthCore Team
Version
1.0.0
Date
2026-06-11
Definition at line 11 of file PatientRegistrationForm.java.
Constructor & Destructor Documentation
PatientRegistrationForm() [1/2]
it.unitn.healthcore.domain.PatientRegistrationForm.PatientRegistrationForm ()
Default constructor required by JPA.
Definition at line 17 of file PatientRegistrationForm.java.
PatientRegistrationForm() [2/2]
it.unitn.healthcore.domain.PatientRegistrationForm.PatientRegistrationForm (String name, String surname, String email, String password, String passwordConfirmation, Integer healthcareCardNumber)
Creates a PatientRegistrationForm with the specified details.
Definition at line 20 of file PatientRegistrationForm.java.
Member Function Documentation
getHealthcareCardNumber()
Integer it.unitn.healthcore.domain.PatientRegistrationForm.getHealthcareCardNumber ()
Healthcare card number getter.
Definition at line 48 of file PatientRegistrationForm.java.
Referenced by it.unitn.healthcore.business.UserService.registerPatient().
getName()
String it.unitn.healthcore.domain.PatientRegistrationForm.getName ()
Creates a PatientRegistrationForm with the specified details, without healthcare card number.
Definition at line 29 of file PatientRegistrationForm.java.
Referenced by it.unitn.healthcore.business.UserService.registerPatient().
getSurname()
String it.unitn.healthcore.domain.PatientRegistrationForm.getSurname ()
Surname getter.
Definition at line 39 of file PatientRegistrationForm.java.
Referenced by it.unitn.healthcore.business.UserService.registerPatient().
setHealthcareCardNumber()
void it.unitn.healthcore.domain.PatientRegistrationForm.setHealthcareCardNumber (Integer healthcareCardNumber)
Healthcare card number setter.
Definition at line 52 of file PatientRegistrationForm.java.
setName()
void it.unitn.healthcore.domain.PatientRegistrationForm.setName (String name)
Name setter.
Definition at line 34 of file PatientRegistrationForm.java.
setSurname()
void it.unitn.healthcore.domain.PatientRegistrationForm.setSurname (String surname)
Surname setter.
Definition at line 44 of file PatientRegistrationForm.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/PatientRegistrationForm.java