HealthCore: it.unitn.healthcore.domain.Department Class Reference
it.unitn.healthcore.domain.Department Class Reference
Entity representing a hospital department, mapped to the "departments" table.
Public Member Functions
Department ()
Department (Hospital hospital, String name, Integer beds, Integer totalStaffPositions)
Creates a Department with full credentials.
List< Equipment > getEquipments ()
void setEquipments (List< Equipment > equipments)
List< Doctor > getDoctors ()
void setDoctors (List< Doctor > doctors)
Integer getDepartmentId ()
void setDepartmentId (Integer departmentId)
Sets the department ID.
String getName ()
Returns the list of equipments associated with the department.
void setName (String name)
Sets the name of the department.
Integer getBeds ()
Returns the available bed number within the department.
void setBeds (Integer beds)
Sets the available bed number within the department.
Integer getTotalStaffPositions ()
Returns the total staff positions within the department.
void setTotalStaffPositions (Integer totalStaffPositions)
Sets the total staff positions within the department.
Hospital getHospital ()
Returns the hospital associated with the department.
void setHospital (Hospital hospital)
Sets the hospital associated with the department.
Detailed Description
Entity representing a hospital department, mapped to the "departments" table.
It uses JPA annotations for ORM mapping to the "departments" table in the database.
Author
HealthCore Team
Version
1.0.0
Date
2026-06-12
Definition at line 18 of file Department.java.
Constructor & Destructor Documentation
Department() [1/2]
it.unitn.healthcore.domain.Department.Department ()
Definition at line 42 of file Department.java.
Department() [2/2]
it.unitn.healthcore.domain.Department.Department (Hospital hospital, String name, Integer beds, Integer totalStaffPositions)
Creates a Department with full credentials.
Definition at line 44 of file Department.java.
Member Function Documentation
getBeds()
Integer it.unitn.healthcore.domain.Department.getBeds ()
Returns the available bed number within the department.
Definition at line 83 of file Department.java.
getDepartmentId()
Integer it.unitn.healthcore.domain.Department.getDepartmentId ()
Definition at line 66 of file Department.java.
getDoctors()
List<Doctor> it.unitn.healthcore.domain.Department.getDoctors ()
Definition at line 58 of file Department.java.
Referenced by it.unitn.healthcore.business.DoctorService.changeDepartment(), and it.unitn.healthcore.business.UserService.registerDoctor().
getEquipments()
List<Equipment> it.unitn.healthcore.domain.Department.getEquipments ()
Definition at line 50 of file Department.java.
getHospital()
Hospital it.unitn.healthcore.domain.Department.getHospital ()
Returns the hospital associated with the department.
Definition at line 99 of file Department.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), it.unitn.healthcore.business.PatientService.bookAppointment(), and it.unitn.healthcore.business.PatientService.getDoctorDescription().
getName()
String it.unitn.healthcore.domain.Department.getName ()
Returns the list of equipments associated with the department.
Definition at line 75 of file Department.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), and it.unitn.healthcore.business.PatientService.getDoctorDescription().
getTotalStaffPositions()
Integer it.unitn.healthcore.domain.Department.getTotalStaffPositions ()
Returns the total staff positions within the department.
Definition at line 91 of file Department.java.
Referenced by it.unitn.healthcore.business.DoctorService.changeDepartment(), and it.unitn.healthcore.business.UserService.registerDoctor().
setBeds()
void it.unitn.healthcore.domain.Department.setBeds (Integer beds)
Sets the available bed number within the department.
Definition at line 87 of file Department.java.
setDepartmentId()
void it.unitn.healthcore.domain.Department.setDepartmentId (Integer departmentId)
Sets the department ID.
Definition at line 70 of file Department.java.
setDoctors()
void it.unitn.healthcore.domain.Department.setDoctors (List< Doctor > doctors)
Definition at line 62 of file Department.java.
setEquipments()
void it.unitn.healthcore.domain.Department.setEquipments (List< Equipment > equipments)
Definition at line 54 of file Department.java.
setHospital()
void it.unitn.healthcore.domain.Department.setHospital (Hospital hospital)
Sets the hospital associated with the department.
Definition at line 103 of file Department.java.
setName()
void it.unitn.healthcore.domain.Department.setName (String name)
Sets the name of the department.
Definition at line 79 of file Department.java.
setTotalStaffPositions()
void it.unitn.healthcore.domain.Department.setTotalStaffPositions (Integer totalStaffPositions)
Sets the total staff positions within the department.
Definition at line 95 of file Department.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/Department.java