HealthCore: it.unitn.healthcore.domain.Appointment Class Reference
it.unitn.healthcore.domain.Appointment Class Reference
Entity representing a scheduled appointment between a Patient and a Doctor, mapped to the "appointments" table.
Public Member Functions
Appointment ()
Appointment (Patient patient, Doctor doctor, LocalDateTime startTime, LocalDateTime endTime)
Creates an Appointment between a patient and a doctor.
Note getNote ()
Returns the appointment ID.
void setNote (Note note)
Sets the note associated with the appointment.
List< Diagnosis > getDiagnoses ()
Returns the list of diagnoses associated with the appointment.
void setDiagnoses (List< Diagnosis > diagnoses)
Sets the list of diagnoses associated with the appointment.
Integer getAppointmentId ()
Returns the appointment ID.
void setAppointmentId (Integer appointmentId)
Sets the appointment ID.
Patient getPatient ()
Returns the patient associated with the appointment.
void setPatient (Patient patient)
Sets the patient associated with the appointment.
Doctor getDoctor ()
Returns the doctor conducting the appointment.
void setDoctor (Doctor doctor)
Sets the doctor conducting the appointment.
LocalDateTime getEndTime ()
Returns the end date and time of the appointment.
void setEndTime (LocalDateTime endTime)
Sets the end date and time of the appointment.
LocalDateTime getStartTime ()
Returns the start date and time of the appointment.
void setStartTime (LocalDateTime startTime)
Sets the start date and time of the appointment.
Detailed Description
Entity representing a scheduled appointment between a Patient and a Doctor, mapped to the "appointments" table.
Author
HealthCore Team
Version
1.0.0
Date
2026-06-12
Definition at line 19 of file Appointment.java.
Constructor & Destructor Documentation
Appointment() [1/2]
it.unitn.healthcore.domain.Appointment.Appointment ()
Definition at line 47 of file Appointment.java.
Appointment() [2/2]
it.unitn.healthcore.domain.Appointment.Appointment (Patient patient, Doctor doctor, LocalDateTime startTime, LocalDateTime endTime)
Creates an Appointment between a patient and a doctor.
Parameters
patient The patient attending the appointment.
doctor The doctor conducting the appointment.
startTime Appointment start date and time.
endTime Appointment end date and time.
Definition at line 56 of file Appointment.java.
Member Function Documentation
getAppointmentId()
Integer it.unitn.healthcore.domain.Appointment.getAppointmentId ()
Returns the appointment ID.
Definition at line 79 of file Appointment.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), and it.unitn.healthcore.business.AppointmentService.getAppointmentDetails().
getDiagnoses()
List<Diagnosis> it.unitn.healthcore.domain.Appointment.getDiagnoses ()
Returns the list of diagnoses associated with the appointment.
Definition at line 71 of file Appointment.java.
getDoctor()
Doctor it.unitn.healthcore.domain.Appointment.getDoctor ()
Returns the doctor conducting the appointment.
Definition at line 95 of file Appointment.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), and it.unitn.healthcore.business.AppointmentService.getAppointmentDetails().
getEndTime()
LocalDateTime it.unitn.healthcore.domain.Appointment.getEndTime ()
Returns the end date and time of the appointment.
Definition at line 103 of file Appointment.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), and it.unitn.healthcore.business.AppointmentService.getAppointmentDetails().
getNote()
Note it.unitn.healthcore.domain.Appointment.getNote ()
Returns the appointment ID.
Definition at line 63 of file Appointment.java.
getPatient()
Patient it.unitn.healthcore.domain.Appointment.getPatient ()
Returns the patient associated with the appointment.
Definition at line 87 of file Appointment.java.
Referenced by it.unitn.healthcore.business.AppointmentService.getAppointmentDetails().
getStartTime()
LocalDateTime it.unitn.healthcore.domain.Appointment.getStartTime ()
Returns the start date and time of the appointment.
Definition at line 111 of file Appointment.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), and it.unitn.healthcore.business.AppointmentService.getAppointmentDetails().
setAppointmentId()
void it.unitn.healthcore.domain.Appointment.setAppointmentId (Integer appointmentId)
Sets the appointment ID.
Definition at line 83 of file Appointment.java.
setDiagnoses()
void it.unitn.healthcore.domain.Appointment.setDiagnoses (List< Diagnosis > diagnoses)
Sets the list of diagnoses associated with the appointment.
Definition at line 75 of file Appointment.java.
setDoctor()
void it.unitn.healthcore.domain.Appointment.setDoctor (Doctor doctor)
Sets the doctor conducting the appointment.
Definition at line 99 of file Appointment.java.
setEndTime()
void it.unitn.healthcore.domain.Appointment.setEndTime (LocalDateTime endTime)
Sets the end date and time of the appointment.
Definition at line 107 of file Appointment.java.
setNote()
void it.unitn.healthcore.domain.Appointment.setNote (Note note)
Sets the note associated with the appointment.
Definition at line 67 of file Appointment.java.
setPatient()
void it.unitn.healthcore.domain.Appointment.setPatient (Patient patient)
Sets the patient associated with the appointment.
Definition at line 91 of file Appointment.java.
setStartTime()
void it.unitn.healthcore.domain.Appointment.setStartTime (LocalDateTime startTime)
Sets the start date and time of the appointment.
Definition at line 115 of file Appointment.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/Appointment.java