HealthCore: it.unitn.healthcore.controller.PatientController Class Reference
it.unitn.healthcore.controller.PatientController Class Reference
PatientController is a REST controller that handles HTTP requests related to patient management and appointment booking for patients.
Public Member Functions
PatientController (PatientService patientService, AppointmentService appointmentService)
Constructor for the PatientController class.
InsurancePlan updateInsurancePlan (@RequestParam Integer planId)
Retrieves the current insurance plan of the authenticated patient.
String getDoctorDescription (@PathVariable("doctorId") Integer doctorId)
Retrieves the current insurance plan of the authenticated patient.
String bookAppointment (@PathVariable Integer doctorId, @RequestParam LocalDateTime startTime, @RequestParam LocalDateTime endTime)
Books an appointment with a specified doctor for the authenticated patient.
String viewFutureAppointments ()
Retrieves a list of future appointments for the authenticated patient.
String viewPastAppointments ()
Retrieves a list of past appointments for the authenticated patient.
String viewAppointmentDetail (@PathVariable Integer appointmentId)
Retrieves the details of a specific appointment by its ID.
void modifyAppointment (@PathVariable Integer appointmentId, @RequestParam LocalDateTime startTime, @RequestParam LocalDateTime endTime)
Modifies the details of an existing appointment for the authenticated patient.
void cancelAppointment (@PathVariable Integer appointmentId)
Cancels an existing appointment for the authenticated patient.
Detailed Description
PatientController is a REST controller that handles HTTP requests related to patient management and appointment booking for patients.
It provides endpoints for patients to manage their insurance plans, view doctor descriptions, book appointments with doctors, and view their appointment history and details.
See also
PatientService
Author
HealthCore Team
Version
1.0.0
Date
2026-06-11
Definition at line 24 of file PatientController.java.
Constructor & Destructor Documentation
PatientController()
it.unitn.healthcore.controller.PatientController.PatientController (PatientService patientService, AppointmentService appointmentService)
Constructor for the PatientController class.
This constructor is used to inject the PatientService and AppointmentService dependencies into the controller. The @Autowired annotation allows Spring to automatically wire the services when creating an instance of the controller.
Parameters
patientService The service that provides business logic related to patients.
appointmentService The service that provides business logic related to appointments.
Definition at line 34 of file PatientController.java.
Member Function Documentation
bookAppointment()
String it.unitn.healthcore.controller.PatientController.bookAppointment (@PathVariable Integer doctorId, @RequestParam LocalDateTime startTime, @RequestParam LocalDateTime endTime)
Books an appointment with a specified doctor for the authenticated patient.
This endpoint is accessible only to users with the 'PATIENT' role. It takes the doctor's ID, start time, and end time as parameters and creates an appointment. It returns a string containing the details of the created appointment, including doctor information, department, and hospital.
Parameters
doctorId The ID of the doctor to book an appointment with.
startTime The start time of the appointment.
endTime The end time of the appointment.
Returns
A string containing the details of the booked appointment.
Definition at line 69 of file PatientController.java.
References it.unitn.healthcore.business.PatientService.bookAppointment(), it.unitn.healthcore.domain.Appointment.getAppointmentId(), it.unitn.healthcore.domain.Doctor.getDepartment(), it.unitn.healthcore.domain.Appointment.getDoctor(), it.unitn.healthcore.domain.User.getEmail(), it.unitn.healthcore.domain.Appointment.getEndTime(), it.unitn.healthcore.domain.Department.getHospital(), it.unitn.healthcore.domain.Department.getName(), it.unitn.healthcore.domain.Hospital.getName(), it.unitn.healthcore.domain.User.getName(), it.unitn.healthcore.domain.Appointment.getStartTime(), and it.unitn.healthcore.domain.User.getSurname().
cancelAppointment()
void it.unitn.healthcore.controller.PatientController.cancelAppointment (@PathVariable Integer appointmentId)
Cancels an existing appointment for the authenticated patient.
This endpoint is accessible only to users with the 'PATIENT' role. It takes the appointment ID as a parameter and cancels the corresponding appointment. It does not return any content in the response.
Parameters
appointmentId The ID of the appointment to cancel.
Definition at line 167 of file PatientController.java.
References it.unitn.healthcore.business.PatientService.cancelAppointment().
getDoctorDescription()
String it.unitn.healthcore.controller.PatientController.getDoctorDescription (@PathVariable("doctorId") Integer doctorId)
Retrieves the current insurance plan of the authenticated patient.
This endpoint is accessible only to users with the 'PATIENT' role. It returns the InsurancePlan object representing the patient's current insurance plan.
Returns
The current InsurancePlan of the patient.
Definition at line 54 of file PatientController.java.
References it.unitn.healthcore.business.PatientService.getDoctorDescription().
modifyAppointment()
void it.unitn.healthcore.controller.PatientController.modifyAppointment (@PathVariable Integer appointmentId, @RequestParam LocalDateTime startTime, @RequestParam LocalDateTime endTime)
Modifies the details of an existing appointment for the authenticated patient.
This endpoint is accessible only to users with the 'PATIENT' role. It takes the appointment ID, new start time, and new end time as parameters and updates the appointment accordingly. It does not return any content in the response.
Parameters
appointmentId The ID of the appointment to modify.
startTime The new start time for the appointment.
endTime The new end time for the appointment.
Definition at line 156 of file PatientController.java.
References it.unitn.healthcore.business.PatientService.modifyAppointment().
updateInsurancePlan()
InsurancePlan it.unitn.healthcore.controller.PatientController.updateInsurancePlan (@RequestParam Integer planId)
Retrieves the current insurance plan of the authenticated patient.
This endpoint is accessible only to users with the 'PATIENT' role. It returns the InsurancePlan object representing the patient's current insurance plan.
Returns
The current InsurancePlan of the patient.
Definition at line 44 of file PatientController.java.
References it.unitn.healthcore.business.PatientService.getCurrentInsurancePlan(), and it.unitn.healthcore.business.PatientService.updateInsurancePlan().
viewAppointmentDetail()
String it.unitn.healthcore.controller.PatientController.viewAppointmentDetail (@PathVariable Integer appointmentId)
Retrieves the details of a specific appointment by its ID.
This endpoint is accessible only to users with the 'PATIENT' role. It returns a string containing the details of the appointment, including doctor information, diagnosis history, and any notes associated with the appointment.
Parameters
appointmentId The ID of the appointment to retrieve.
Returns
A string containing the details of the specified appointment.
Definition at line 144 of file PatientController.java.
References it.unitn.healthcore.business.AppointmentService.getAppointmentDetails().
viewFutureAppointments()
String it.unitn.healthcore.controller.PatientController.viewFutureAppointments ()
Retrieves a list of future appointments for the authenticated patient.
This endpoint is accessible only to users with the 'PATIENT' role. It returns a string representation of each future appointment, including the appointment ID, start and end times, and doctor information.
Returns
A string containing the details of future appointments for the patient.
Definition at line 101 of file PatientController.java.
References it.unitn.healthcore.business.AppointmentService.getFutureAppointments().
viewPastAppointments()
String it.unitn.healthcore.controller.PatientController.viewPastAppointments ()
Retrieves a list of past appointments for the authenticated patient.
This endpoint is accessible only to users with the 'PATIENT' role. It returns a string representation of each past appointment, including the appointment ID, start and end times, and doctor information.
Returns
A string containing the details of past appointments for the patient.
Definition at line 122 of file PatientController.java.
References it.unitn.healthcore.business.AppointmentService.getPastAppointments().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/controller/PatientController.java