HealthCore: it.unitn.healthcore.domain.Shift Class Reference
it.unitn.healthcore.domain.Shift Class Reference
Entity representing a work shift for a doctor, mapped to the "shifts" table.
Public Member Functions
Shift ()
Default constructor required by JPA.
Shift (Doctor doctor, LocalDateTime startTime, LocalDateTime endTime)
Creates a Shift for a given doctor and time period.
Integer getShiftId ()
Returns the shift ID.
void setShiftId (Integer shiftId)
Sets the shift ID.
Doctor getDoctor ()
Returns the doctor assigned to the shift.
void setDoctor (Doctor doctor)
Sets the doctor assigned to the shift.
LocalDateTime getStartTime ()
Returns the start time of the shift.
void setStartTime (LocalDateTime startTime)
Sets the start time of the shift.
LocalDateTime getEndTime ()
Returns the end time of the shift.
void setEndTime (LocalDateTime endTime)
Sets the end time of the shift.
Detailed Description
Entity representing a work shift for a doctor, mapped to the "shifts" table.
@detail Each Shift is associated with a Doctor and has a start and end time, indicating when the doctor is scheduled to work.
Author
HealthCore Team
Version
1.0.0
Date
2026-06-12
Definition at line 18 of file Shift.java.
Constructor & Destructor Documentation
Shift() [1/2]
it.unitn.healthcore.domain.Shift.Shift ()
Default constructor required by JPA.
Definition at line 29 of file Shift.java.
Shift() [2/2]
it.unitn.healthcore.domain.Shift.Shift (Doctor doctor, LocalDateTime startTime, LocalDateTime endTime)
Creates a Shift for a given doctor and time period.
Parameters
doctor The doctor assigned to the shift.
startTime The start date and time of the shift.
endTime The end date and time of the shift.
Definition at line 37 of file Shift.java.
Member Function Documentation
getDoctor()
Doctor it.unitn.healthcore.domain.Shift.getDoctor ()
Returns the doctor assigned to the shift.
Definition at line 52 of file Shift.java.
Referenced by it.unitn.healthcore.business.DoctorService.deleteShift(), and it.unitn.healthcore.business.DoctorService.modifyShift().
getEndTime()
LocalDateTime it.unitn.healthcore.domain.Shift.getEndTime ()
Returns the end time of the shift.
Definition at line 68 of file Shift.java.
Referenced by it.unitn.healthcore.business.DoctorService.modifyShift().
getShiftId()
Integer it.unitn.healthcore.domain.Shift.getShiftId ()
Returns the shift ID.
Definition at line 44 of file Shift.java.
getStartTime()
LocalDateTime it.unitn.healthcore.domain.Shift.getStartTime ()
Returns the start time of the shift.
Definition at line 60 of file Shift.java.
Referenced by it.unitn.healthcore.business.DoctorService.modifyShift().
setDoctor()
void it.unitn.healthcore.domain.Shift.setDoctor (Doctor doctor)
Sets the doctor assigned to the shift.
Definition at line 56 of file Shift.java.
setEndTime()
void it.unitn.healthcore.domain.Shift.setEndTime (LocalDateTime endTime)
Sets the end time of the shift.
Definition at line 72 of file Shift.java.
Referenced by it.unitn.healthcore.business.DoctorService.modifyShift().
setShiftId()
void it.unitn.healthcore.domain.Shift.setShiftId (Integer shiftId)
Sets the shift ID.
Definition at line 48 of file Shift.java.
setStartTime()
void it.unitn.healthcore.domain.Shift.setStartTime (LocalDateTime startTime)
Sets the start time of the shift.
Definition at line 64 of file Shift.java.
Referenced by it.unitn.healthcore.business.DoctorService.modifyShift().
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/Shift.java