HealthCore: it.unitn.healthcore.domain.Doctor Class Reference
it.unitn.healthcore.domain.Doctor Class Reference
Represents a doctor in our system, extending the general User class.
Public Member Functions
Doctor ()
Default constructor required by JPA.
Doctor (String name, String surname, String email, String password, Department department, String specialization, Double appointmentPrice)
Creates a Doctor with full credentials.
Doctor (String name, String surname, String email, String password, Department department)
Creates a Doctor with full credentials.
String toString ()
Creates a Doctor with full credentials.
List< Appointment > getAppointments ()
Appointment getter.
void setAppointments (List< Appointment > appointments)
Appointment setter.
List< EquipmentDoctor > getEquipments ()
Equipment getter.
void setEquipments (List< EquipmentDoctor > equipments)
Appointment getter.
List< Shift > getShifts ()
Shift getter.
void setShifts (List< Shift > shifts)
Shift setter.
Department getDepartment ()
Department getter.
void setDepartment (Department department)
Department setter.
String getSpecialization ()
Specialization getter.
void setSpecialization (String specialization)
Specialization setter.
Double getAppointmentPrice ()
Appointment price getter.
void setAppointmentPrice (Double appointmentPrice)
Appointment price setter.
Public Member Functions inherited from it.unitn.healthcore.domain.User
User ()
Default constructor required by JPA.
User (String name, String surname, String email, String password)
Creates a User with full credentials.
Integer getId ()
Returns a string representation of the User.
void setId (Integer id)
Sets the user ID.
String getName ()
Returns the first name of the user.
void setName (String name)
Sets the first name of the user.
String getSurname ()
Returns the last name of the user.
void setSurname (String surname)
Sets the last name of the user.
String getEmail ()
Returns the email address of the user.
void setEmail (String email)
Sets the email address of the user.
String getPassword ()
Returns the password of the user.
void setPassword (String password)
Sets the password of the user.
Detailed Description
Represents a doctor in our system, extending the general User class.
T It uses JPA annotations for ORM mapping to the "doctors" table in the database.
Author
HealthCore Team
Version
1.0.0
Date
2026-06-11
Definition at line 18 of file Doctor.java.
Constructor & Destructor Documentation
Doctor() [1/3]
it.unitn.healthcore.domain.Doctor.Doctor ()
Default constructor required by JPA.
Definition at line 31 of file Doctor.java.
Doctor() [2/3]
it.unitn.healthcore.domain.Doctor.Doctor (String name, String surname, String email, String password, Department department, String specialization, Double appointmentPrice)
Creates a Doctor with full credentials.
Parameters
name First name.
surname Last name.
email Email address.
password Account password.
Definition at line 40 of file Doctor.java.
Doctor() [3/3]
it.unitn.healthcore.domain.Doctor.Doctor (String name, String surname, String email, String password, Department department)
Creates a Doctor with full credentials.
Definition at line 48 of file Doctor.java.
Member Function Documentation
getAppointmentPrice()
Double it.unitn.healthcore.domain.Doctor.getAppointmentPrice ()
Appointment price getter.
Definition at line 112 of file Doctor.java.
Referenced by it.unitn.healthcore.business.PatientService.getDoctorDescription().
getAppointments()
List<Appointment> it.unitn.healthcore.domain.Doctor.getAppointments ()
Appointment getter.
Definition at line 65 of file Doctor.java.
getDepartment()
Department it.unitn.healthcore.domain.Doctor.getDepartment ()
Department getter.
Definition at line 96 of file Doctor.java.
Referenced by it.unitn.healthcore.controller.PatientController.bookAppointment(), it.unitn.healthcore.business.PatientService.bookAppointment(), and it.unitn.healthcore.business.PatientService.getDoctorDescription().
getEquipments()
List<EquipmentDoctor> it.unitn.healthcore.domain.Doctor.getEquipments ()
Equipment getter.
Definition at line 76 of file Doctor.java.
getShifts()
List<Shift> it.unitn.healthcore.domain.Doctor.getShifts ()
Shift getter.
Definition at line 87 of file Doctor.java.
Referenced by it.unitn.healthcore.business.DoctorService.addShift(), it.unitn.healthcore.business.DoctorService.getCurrentDoctorShifts(), it.unitn.healthcore.business.PatientService.getDoctorDescription(), and it.unitn.healthcore.business.DoctorService.modifyShift().
getSpecialization()
String it.unitn.healthcore.domain.Doctor.getSpecialization ()
Specialization getter.
Definition at line 104 of file Doctor.java.
Referenced by it.unitn.healthcore.business.PatientService.getDoctorDescription().
setAppointmentPrice()
void it.unitn.healthcore.domain.Doctor.setAppointmentPrice (Double appointmentPrice)
Appointment price setter.
Definition at line 116 of file Doctor.java.
setAppointments()
void it.unitn.healthcore.domain.Doctor.setAppointments (List< Appointment > appointments)
Appointment setter.
Definition at line 70 of file Doctor.java.
setDepartment()
void it.unitn.healthcore.domain.Doctor.setDepartment (Department department)
Department setter.
Definition at line 100 of file Doctor.java.
Referenced by it.unitn.healthcore.business.DoctorService.changeDepartment().
setEquipments()
void it.unitn.healthcore.domain.Doctor.setEquipments (List< EquipmentDoctor > equipments)
Appointment getter.
Definition at line 82 of file Doctor.java.
setShifts()
void it.unitn.healthcore.domain.Doctor.setShifts (List< Shift > shifts)
Shift setter.
Definition at line 92 of file Doctor.java.
setSpecialization()
void it.unitn.healthcore.domain.Doctor.setSpecialization (String specialization)
Specialization setter.
Definition at line 108 of file Doctor.java.
toString()
String it.unitn.healthcore.domain.Doctor.toString ()
Creates a Doctor with full credentials.
Definition at line 56 of file Doctor.java.
The documentation for this class was generated from the following file:
healthcore/src/main/java/it/unitn/healthcore/domain/Doctor.java